### ISSUE TITLE
Crash on receive event from python server

### ISSUE THREAD

**Issue by getnamo** [getnamo/socketio-client-ue4#102]
Issue reference https://forums.unrealengine.com/development-discussion/engine-source-github/82790-plugin-socket-io-client?p=1543233#post1543233

**Comment by getnamo** [comment]
Maybe ```As String``` failure on array responses?

**Comment by sattle** [comment]
Hi,

Thanks for the answer and openning the issue.

I tried the two possibilities you pointed out. Nothing changed. 


![2018-10-29_crash_log_and_server_code](https://user-images.githubusercontent.com/6931957/47644010-517f1000-db6d-11e8-8c2d-722ef3091f17.JPG)
![2018-10-29_crash_log_and_server_code_bis](https://user-images.githubusercontent.com/6931957/47644011-517f1000-db6d-11e8-93a7-62aee034417a.JPG)


I have tried to just print the name of the event received and the result is the same.

![bind_and_on_event](https://user-images.githubusercontent.com/6931957/47644131-a4f15e00-db6d-11e8-8fa2-da62e0c30edc.JPG)

I made a client in python, and I have no communication problems between my client and my server.

I'm still under the impression it can't bind my 'reply' event...
I still don't know  where that comes from => 
![class_none](https://user-images.githubusercontent.com/6931957/47644192-c6524a00-db6d-11e8-84b3-9fc4bb0efdcf.JPG)

**Comment by getnamo** [comment]
This is very strange, from the logs you can see that the replies work and that you are receiving the information, but that it then crashes anyway due to an unbound lambda. BTW If you compile the project with the plugin you'll get .pdb files which will make the log a bit more verbose when it crashes. 

I did check ```As String``` with different configs (using node.js server though) and that part doesn't cause crashes, need to explore another avenue. What version of socket.io is running on the python server, I might need to duplicate the python server setup to see if I can get a replication of the bug.

**Comment by sattle** [comment]
I'm using the latest version (2.0.0) : https://pypi.org/project/python-socketio/

**Comment by sattle** [comment]
Hi,

So, I tried to create a new blank c++ project (without starting content).
I then downloaded the latest version of the plugin (socketio-client-v0.9.0-UE4.20.7z), took the plugins folder and I added it to my project root folder.
 I opened the project and recompile it and got those logs.

![log_2018-10-30_compile_error](https://user-images.githubusercontent.com/6931957/47720480-405a0000-dc4e-11e8-98fd-f3f557404f22.JPG)

I'm missing something in the process ?

**Comment by getnamo** [comment]
That output seems to think everything is built, you probably need to clean/rebuild to force it to rebuild.

That said I've got this error replicating on my side now. I wrote out your image server into a [server.py](https://gist.github.com/getnamo/531421d4c1382f35059e9de257c1fbfa) gist and installed the dependencies with my pdbs I'm getting more details:

```
Assertion failed: false [File:C:\Program Files\Epic Games\UE_4.20\Engine\Source\Runtime\Core\Public\Templates/Function.h] [Line: 275] Attempting to call an unbound TFunction!

UE4Editor_Core!FDebug::AssertFailed() [d:\build\++ue4\sync\engine\source\runtime\core\private\misc\assertionmacros.cpp:425]
UE4Editor_SocketIOClient!<lambda_ed515017232aae7d0293e6bc3080dcf2>::operator()() [c:\users\admin\documents\github\socketiowork\plugins\socketio-client-ue4\source\socketioclient\private\socketionative.cpp:122]
UE4Editor_SocketIOClient!TGraphTask<FFunctionGraphTask>::ExecuteTask() [c:\program files\epic games\ue_4.20\engine\source\runtime\core\public\async\taskgraphinterfaces.h:830]
UE4Editor_Core!FNamedTaskThread::ProcessTasksNamedThread() [d:\build\++ue4\sync\engine\source\runtime\core\private\async\taskgraph.cpp:665]
UE4Editor_Core!FNamedTaskThread::ProcessTasksUntilIdle() [d:\build\++ue4\sync\engine\source\runtime\core\private\async\taskgraph.cpp:585]
UE4Editor_Engine!FFrameEndSync::Sync() [d:\build\++ue4\sync\engine\source\runtime\engine\private\unrealengine.cpp:9962]
UE4Editor!FEngineLoop::Tick() [d:\build\++ue4\sync\engine\source\runtime\launch\private\launchengineloop.cpp:3655]
UE4Editor!GuardedMain() [d:\build\++ue4\sync\engine\source\runtime\launch\private\launch.cpp:166]
UE4Editor!GuardedMainWrapper() [d:\build\++ue4\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:144]
UE4Editor!WinMain() [d:\build\++ue4\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:223]
UE4Editor!__scrt_common_main_seh() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283]
kernel32
ntdll
```

which is pointing to https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SocketIOClient/Private/SocketIONative.cpp#L122. I'll have a look with a debugger.

**Comment by getnamo** [comment]
Ok so the crash appears to be happening because the python server emits a callback to the client even if none is specified by the client, this is divergent behavior from node.js socket.io server, but nothing we can't work around.

That behavior is catching a legitimate bug in the client though, which is calling a TFunction without checking if it's valid. 
I merged a fix here: https://github.com/getnamo/socketio-client-ue4/pull/103/commits/0e6f6c93d168b462e242bfaf2f1d7627d81f7ecb

if you re-pull the master on your end and compile it should now work.

**Comment by getnamo** [comment]
Made a new release to make things easier: https://github.com/getnamo/socketio-client-ue4/releases/tag/0.9.5

**Comment by sattle** [comment]
Hi, 

I tried the new release and it's working now.

Thanks for the help and nice work with this plugin !

**Comment by getnamo** [comment]
Awesome, closing issue.
