### ISSUE TITLE
False positive warning C5046 from CoreUtilityBPLibrary.cpp.

### ISSUE THREAD

**Issue by i3oi3o** [getnamo/socketio-client-ue4#104]
In Unreal Engine 4.20 with Visual Studio 2017 version 15.8.4, You will get warning C5046 from CoreUtilityBPLibrary.cpp.

The warning come from using ENQUEUE_UNIQUE_RENDER_COMMAND_ONEPARAMETER macro within C++ lambda.

Someone already report this false positive to visual studio team -> https://developercommunity.visualstudio.com/content/problem/370665/c5046-false-positive-example.html

Should we suppress this warning?

**Comment by getnamo** [comment]
added pragma barrier in: https://github.com/getnamo/socketio-client-ue4/commit/5c3b12df0352addfa4e8970b1fc0c4f41ddbc7f8#diff-02c2b8bed248a1254ac86a3a86777a19
