### ISSUE TITLE
Can anyone give me an example about this place?  SIOClientComponent->OnNativeEvent   

### ISSUE THREAD

**Issue by zoutao212** [getnamo/socketio-client-ue4#106]
![image](https://user-images.githubusercontent.com/39266302/49279261-f620a480-f4c1-11e8-98be-c13818ec56b1.png)
![image](https://user-images.githubusercontent.com/39266302/49279283-03d62a00-f4c2-11e8-863a-63b77cf0e7fb.png)
How should I write to enable VS breakpoints to work, or to output a prompt in UE4?

**Comment by getnamo** [comment]
VS should catch breakpoints within the lambda, make sure you're using Debug Editor Target when debugging so that your operations don't get optimized away by the compiler.

NB: The ```TSharedPtr<FJsonValue>& Message``` is a standard ue4 type http://api.unrealengine.com/INT/API/Runtime/Json/Dom/FJsonValue/

If serverlist is an array try 
```c++
TArray < TSharedPtr < FJsonValue > > ServerListArray = Message->AsArray();
```
or 
```c++
auto ServerListArray = Message->AsArray();
```
and work from there. If it's an object then AsObject() etc...

**Comment by zoutao212** [comment]
Thank you very much for your answer.
I have solved this problem today.
I will post my code next Monday.
The reason the code didn't work before was because there was no waiting for the link to be created.

**Comment by zoutao212** [comment]
// Fill out your copyright notice in the Description page of Project Settings.

#include "MyCharacter.h"
#include "SIOJConvert.h"

// Sets default values
AMyCharacter::AMyCharacter()
{
 	// Set this character to call Tick() every frame.  
	// You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;

	SIOClientComponent = CreateDefaultSubobject<USocketIOClientComponent>
		(TEXT("SocketIOClientComponent"));

	//SIOClientComponent->AddressAndPort = FString("http://127.0.0.1:3001");
	SIOClientComponent->bShouldAutoConnect = false;
}

// Called when the game starts or when spawned
void AMyCharacter::BeginPlay()
{
	Super::BeginPlay();

	// 先要Create成功 才能绑定事件回调
	// 先要Create成功  才能调用Connect
	// 绑定事件回调和Connect 可以同时进行
	// Create 和 Connect 都是异步等待操作
	SIOClientComponent->Connect(FString("http://127.0.0.1:3001"));

	// 此时SIOClientComponent->bIsConnected 是 false

	// 绑定事件回调
	SIOClientComponent->OnNativeEvent(FString("server list"), []
	(const FString& Event, const TSharedPtr<FJsonValue>& Message)
	{
		if (!Event.IsEmpty())
		{
			FString JsonString = USIOJConvert::ToJsonString(Message);
			UE_LOG(LogTemp, Warning, TEXT("server list : %s"), *JsonString);
		}
	}, FString(TEXT("/")));

	// 可以发送请求，并且会成功，
	SIOClientComponent->EmitNative(FString("server list"), FString("server list"));

	SIOClientComponent->EmitNative(FString("chat message"), FString::SanitizeFloat(1.0f));

}

// Called every frame
void AMyCharacter::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

	// SIOClientComponent->bIsConnected == true 

}

// Called to bind functionality to input
void AMyCharacter::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)
{
	Super::SetupPlayerInputComponent(PlayerInputComponent);

}
