### ISSUE TITLE
includes broken (Edit: missing SocketIOLib in public dependency modules)

### ISSUE THREAD

**Issue by tgrothm** [getnamo/socketio-client-ue4#110]
Any way I install the plugin (from marketplace too) I get this error:

**fatal error C1083: Cannot open include file: 'sio_client.h': No such file or directory**

If I change the include from `#include "sio_client.h"` to `#include "SocketIOLib/Public/sio_client.h"` it will find the file but I will get:

**error C2079: 'socket' uses undefined class 'sio::SOCKETIOLIB_API'**

.
.

I am on UE4.21 trying to use the plugin via c++

**Comment by tgrothm** [comment]
nevermind... I just failed to add the proper PublicDependencyModules in my plugin

**Comment by chuan9** [comment]
@getnamo @tgrothm Hi, I get the same error, my unreal version is 4.21.2.
 and I added it into my projedct build.cs, its config is as bellows:

PublicDependencyModuleNames.AddRange(new string[] { "Core", "CoreUObject", "Engine", "InputCore", "SocketIOClient" });

I tried to install it from marketplace and it failed, then I install it to local plugins folder, it get the same error. Can you help have a look at this?

**Comment by chuan9** [comment]
@getnamo I fallback to unreal 4.20.3, it works, can you help have look at this? Really want to use it on the latest unreal.

**Comment by tgrothm** [comment]
I'm sorry but I did not use it in the end so I can't help

**Comment by getnamo** [comment]
I'll have a look into a basic C++ example again to see if anything broke.

**Comment by getnamo** [comment]
Ok in the 4.21 build I refactored how the library was compiled which means you now need also add the _SocketIOLib_ module as a dependency in any project you wish to use the C++ api.

Steps: Inside your project build.cs, add _SocketIOClient_ and _SocketIOLib_ (this is the new one)

so it should look like something like this

```c#
PublicDependencyModuleNames.AddRange(new string[] { "Core", "CoreUObject", "Engine", "InputCore", "SocketIOClient", "SocketIOLib" });
```

and it should now work as before. The readme has been clarified to reflect this change.

**Comment by chuan9** [comment]
@getnamo Quickly fix. Thx

**Comment by chuan9** [comment]
@getnamo Hi, I've run this demo, and have a question in your demo for c++, how to get the Message content which can be print in UE_LOG in this section
···
SIOClientComponent->OnNativeEvent(FString("MyEvent"), [](const FString& Event, const TSharedPtr<FJsonValue>& Message)
{
	//Called when the event is received
}, FString("Optional Namespace"));
···

**Comment by getnamo** [comment]
If you're getting linker errors, add "Json" and "SIOJson" to your public dependencies. [Updated the C++ readme](https://github.com/getnamo/socketio-client-ue4#setup) with those instructions as they're almost always used in practice.

If you compiled, but can't receive your event, make sure to omit the namespace variable to use the default namespace ("/"); having this in the call is optional.

So your example should be

```c++
SIOClientComponent->OnNativeEvent(FString("MyEvent"), [](const FString& Event, const TSharedPtr<FJsonValue>& Message)
{
	FString msg = Message->AsString();
	UE_LOG(LogTemp, Warning, TEXT("hello:%s"), *msg);
});
```

Note that "OnNativeEvent" is equivalent to the blueprint "BindEventToFunction", you should only call it once e.g. on beginplay, not every tick.

**Comment by chuan9** [comment]
@getnamo Yes, it works. Thank you very much. By the way, the notes is very helpful!☺
