### ISSUE TITLE
SocketIO will slow down tick function

### ISSUE THREAD

**Issue by chuan9** [getnamo/socketio-client-ue4#112]
@getnamo Hi, I add SIOClientComponent for a pawn, the code is as bellow:
in the BeginPlay:
```
	SIOClientComponent->OnNativeEvent(FString("CMD_FORWARD"), [=](const FString& Event, const TSharedPtr<FJsonValue>& Message)
	{
		FString name = Message->AsString();
		UE_LOG(LogTemp, Warning, TEXT("hello:%s"), *name);
	}, FString(""));
```
in the Tick
```
	counter += 1;
	FString value = FString::SanitizeFloat(counter);
	UE_LOG(LogTemp, Warning, TEXT("Tick MoveForward:%s"), *value);
```
When CMD_FORWARD is not triggered, counter log in tick will refresh about 60fps, when the event was triggered, The counter log in tick will refresh about 1 fps. 
It will slow down other functions severely in Tick for the pawn, I've no idea, can u help have a look?

**Comment by getnamo** [comment]
can you try with namespace "/" by removing the namespace? e.g.

```c++
SIOClientComponent->OnNativeEvent(FString("CMD_FORWARD"), [=](const FString& Event, const TSharedPtr<FJsonValue>& Message)
	{
		FString name = Message->AsString();
		UE_LOG(LogTemp, Warning, TEXT("hello:%s"), *name);
	});
```

**Comment by chuan9** [comment]
@getnamo Hi, I'm on win10, and UE version is 4.21.2. Tried your solution, it's the same result. But, I found that when I put the cursor in the viewport, everything is ok. Maybe it's related to implementation in Unreal. Anyway, I can use it, thanks for your quick response.

**Comment by getnamo** [comment]
try ```t.IdleWhenNotForeground=0```
