### ISSUE TITLE
When support 4.14?

### ISSUE THREAD

**Issue by xiaoheitwo** [getnamo/socketio-client-ue4#12]
This plugin is very usefull ,thanks. Can you tell us when support 4.14?

**Comment by getnamo** [comment]
Planning on 4.14 update within a week.

**Comment by xiaoheitwo** [comment]
fantastic fantastic fantastic

**Comment by getnamo** [comment]
updated for 4.14: https://github.com/getnamo/socketio-client-ue4/releases/tag/0.4.1
