### ISSUE TITLE
Couldn't communicate with python server

### ISSUE THREAD

**Issue by yingbo-chen** [getnamo/socketio-client-ue4#120]
Python server shows that it is connected however, UE4 log says socketio invalid connection lost, 
Im not really sure what's wrong. Python server is fine with js socketio.

Thanks

**Comment by getnamo** [comment]
have you tried https://pypi.org/project/python-socketio/?

Also are you using an ssl connection?

**Comment by yingbo-chen** [comment]
somehow I made it work with ue emitting first then receive an event, if I just have the server emit it wont work.

**Comment by getnamo** [comment]
Do you have a simple python example that replicates this bug?

**Comment by KhalidAtawy** [comment]
Okay, may you tell me if there is a problem with this code, please?

`from flask import Flask, render_template, request
from flask_socketio import SocketIO, emit

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)


@app.route('/')
def index():
    return render_template('index.html')


@socketio.on('chat message')
def handle_my_custom_event(json):
    print(request.sid)
    print('received json: ' + str(json))
    emit('chat message', json, broadcast=True)


@socketio.on('connect')
def handle_my_custom_event():
    print(request.sid)
    print('received json: Connected')


if __name__ == '__main__':
    socketio.run(app)`

and I'm receiving this error when trying to connect.

`a27a567328004664844b6c6ce5088eb4
received json: Connected
127.0.0.1 - - [06/Feb/2020 11:00:53] "GET /socket.io/?EIO=4&transport=websocket&t=1580979653 HTTP/1.1" 400 -
`

Any help would be appreciated

**Comment by getnamo** [comment]
Copied into the newer issue, closing here
