### ISSUE TITLE
Broken MarketplaceURL in uplugin descriptor file

### ISSUE THREAD

**Issue by seon-geun** [getnamo/socketio-client-ue4#121]
I think the MarketplaceURL might need to be changed to
com.epicgames.launcher://ue/marketplace/slug/socket-io-client
instead of current
com.epicgames.launcher://ue/marketplace/content/770c3db686a948e09ccb208705a8e736
Thank you all so much for the plugin by the way.

**Comment by getnamo** [comment]
Thanks for spotting this, if you'd like to make a pull request with the update, I'll merge it.
