### ISSUE TITLE
Crashing when disconnecting and attempting to reconnect

### ISSUE THREAD

**Issue by enfarious** [getnamo/socketio-client-ue4#122]
Using BPs for everything, I keep having both game and editor crash if I call SocketIOClient->Disconnect and attempt to later call SocketIOClient->Connect again. 
Even if I don't call Connect again it will attempt to Reconnect to my server, which I think shouldn't be the case as I intentionally closed the connection by calling Disconnect.
I have ShouldAutoConnect set to false as well, it still attempts to reconnect and leads to game/editor crashing.
When calling Connect (or it attempting to reconnect) I also see that the connection is opened, server gets it and responds, but the connect event (I used event here not function, I don't imagine that is the issue?) never fires again. 
All of this is after successful connection on the first go round.
Is there something I need to do to reset SocketIOClient between connect/disconnect?

**Comment by getnamo** [comment]
What platform/unreal version/plugin version? Do you have a minimal example project you can share that replicates this bug? What are you using as the server (node.js or python)?

**Comment by enfarious** [comment]
Win10 UE4.22 Most recent plugin from github
I'm using Node.js 10.15.3 for the server
I tested with the example server and example client to try to find the issue
The webclient connects, disconnects and reconnects just fine all chat functionality is present and it does not continuously disconnect and try again.
The UE4 client however does, for testing I stopped and restarted the server with the game client still running, it never has the connect event fire again and just keeps trying. 

I found today that in my client the crash is actually from a "Get XXX Field" node, the field I was attempting to get wasn't there in the JSON which ended with crashing. At least that is how it appeared in the logs. I'm not sure now if the two things are actually related, I'll have to explore a bit more.

**Comment by iambeeblebrox** [comment]
Have you made any progress with this? I am also in a situation where I am not receiving Connect events.

**Comment by enfarious** [comment]
I haven't, I've put that project on hold for awhile. I'm hoping that a fix comes because I really like the rest of this plugin.

**Comment by yuchengzhong** [comment]
I got the same problem.
ConnectionProblems can be called,but when it turns to OnFail,the engine crashed.
In Development mode it doesnt have this problem.Only if I run a Disturbution and Shipping this will happen.

**Comment by getnamo** [comment]
Can anyone with this problem try https://github.com/getnamo/socketio-client-ue4/releases/tag/v1.1.0e(1.0.24) release and see this issue persists?

**Comment by enfarious** [comment]
I'll try and get that tested over the weekend.
