### ISSUE TITLE
A question about 'Emit with callback':

### ISSUE THREAD

**Issue by qb0813** [getnamo/socketio-client-ue4#123]
I wonder when the function like onGetMsg get called?
![图片](https://user-images.githubusercontent.com/41063123/56704004-16d1eb00-673e-11e9-8e18-8022bbd76363.png)

Thanks a lot!

**Comment by getnamo** [comment]
if your server has something like 

```javascript
const io = require('socket.io')(http);

io.on('connection', function(socket){
	
	//...

	socket.on('get data', function(msg, callback){
		//let's say your data is an object
		result = {};
	
		/* do something here to get your data */
		
		//callback with the results, this will call your 'OnGetMsg' inside your blueprint
		callback(result);
	});
};
```

Note that the server doesn't know specifics about your callback function on bp side other than it's a parameter it can use to call like a normal js function. See https://socket.io/docs/server-api/#socket-on-eventName-callback for server API details.
