### ISSUE TITLE
build android error from ue4.20

### ISSUE THREAD

**Issue by lwglwg** [getnamo/socketio-client-ue4#125]
UATHelper: 打包 (Android（ASTC）):     C:/siocpp-ndk/sio-client/android/../../boost/android/boost/asio/detail/impl/epoll_reactor.ipp:463: error: undefined reference to 'epoll_create1'
UATHelper: 打包 (Android（ASTC）):     clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
UATHelper: 打包 (Android（ASTC）):   ERROR: UBT ERROR: Failed to produce item: F:\luoyazhanji\Game\Binaries\Android\Sword_VS_Gun-Android-Shipping-armv7-es2.so

**Comment by getnamo** [comment]
Android is only supported from the 4.22 build and onward (v1.0.0). You may have success in using the 4.22 build and recompiling it for 4.20 as they should be compatible in theory

**Comment by lwglwg** [comment]
Thank you for your reply. Is there any plan to support 4.20 android

**Comment by lwglwg** [comment]
4.22 there is a bug. After the client successfully connects to the server, manually disconnect the network for a few seconds and then connect to the network. At this time, the connection will be automatically successful, but it will disconnect and the it will continue to reconnect.Version 4.20 doesn't have this problem。

**Comment by getnamo** [comment]
separate issue, tracked here: https://github.com/getnamo/socketio-client-ue4/issues/126 closing
