### ISSUE TITLE
Windows Build Error

### ISSUE THREAD

**Issue by doganarif** [getnamo/socketio-client-ue4#128]
This module was most likely flagged for being included in a precomplied build - set 'PrecompileForTargets = PrecompileTargetsType.Any;' in SocketIOClient.build.cs

**Comment by getnamo** [comment]
Might be useful to expand with logs, details, and steps to reproduce this error

**Comment by warriorthereal** [comment]
I did everything on docs but i having this issue : 

LNK1181  Intermediate\Build\Win64\UE4Editor\Development\SocketIOClient\UE4Editor-SocketIOClient.lib

**Comment by getnamo** [comment]
Are you building from visual studio or are you packaging from menu? Did you clear intermediate folder and do a full rebuild? Is this the GitHub plugin or from marketplace? Which plugin version for which engine version? Need more details

**Comment by Sere1** [comment]
Building from ue and clear intermediate folder. It's a Github plugin.  Engine version 4.22.3.

**Comment by getnamo** [comment]
Is the plugin placed inside your game project or the editor plugins folder? By building from ue can you confirm you mean packaging?

**Comment by Sere1** [comment]
inside my game project and i mean packaging
