### ISSUE TITLE
where will I add

### ISSUE THREAD

**Issue by Sere1** [getnamo/socketio-client-ue4#129]
where will I add this code
 SIOClientComponent = CreateDefaultSubobject<USocketIOClientComponent>(TEXT("SocketIOClientComponent"));

**Comment by Sere1** [comment]
and add USocketIoClientComponent to your actor of choice via e.g. a UProperty

and CreateDefaultSubobject in your constructor. How can i add USocketIoClientComponent?

**Comment by getnamo** [comment]
CreateDefaultSubobject is used in the constructor, otherwise just use NewObject anywhere else. As long as it's a property it will be protected from garbage collection.

**Comment by Sere1** [comment]
can you add a example maybe ?
