### ISSUE TITLE
large Packet Error

### ISSUE THREAD

**Issue by OHHyeonGyu** [getnamo/socketio-client-ue4#130]
An error has occurred.
If BufferSize is low, there is no problem. When BufferSize becomes large, Trnaport Error occurs and DisConnect is done.
![image](https://user-images.githubusercontent.com/51893487/60642300-5cabdd80-9e6a-11e9-8c90-ad0c0e235b59.png) Success
![image](https://user-images.githubusercontent.com/51893487/60642334-81a05080-9e6a-11e9-9829-1d72f6f779a5.png) Failed
![image](https://user-images.githubusercontent.com/51893487/60642420-b7ddd000-9e6a-11e9-8afc-98aaa2e73456.png) TCP Packet

**Comment by getnamo** [comment]
What's the size of buffer that creates this bug? What would recommend as a way to replicate it?

**Comment by OHHyeonGyu** [comment]
> What's the size of buffer that creates this bug? What would recommend as a way to replicate it?

What do you mean exactly when you mentioned the word, replicate? Additionally, if you are talking about the size of buffer, it is mentioned in the screenshot and the size is over about 131,072.

**Comment by OHHyeonGyu** [comment]
[socketio-client-ue4-example-master.zip](https://github.com/getnamo/socketio-client-ue4/files/3361656/socketio-client-ue4-example-master.zip)
This is the sample we were testing.

**Comment by OHHyeonGyu** [comment]
![image](https://user-images.githubusercontent.com/51893487/60707641-2c863c80-9f47-11e9-937d-3e8379d8768e.png)
Frame 4950 is strange

**Comment by getnamo** [comment]
Interesting. I was able to replicate this by sending a large JSON test via the chat app. Then it disconnects as you mentioned and falls into the same loop as https://github.com/getnamo/socketio-client-ue4/issues/126. Will check large buffers to see if they cause the same issue. Seems like a regression from an earlier version TBC.

**Comment by getnamo** [comment]
Can confirm this is an issue for large binaries too. Currently recommended to rollback to https://github.com/getnamo/socketio-client-ue4/releases/tag/0.10.0 until this issue gets addressed.

**Comment by getnamo** [comment]
note: updating asio to 1.12 with unreal compile fixes seems to have addressed this bug in preliminary tests (https://github.com/getnamo/socketio-client-ue4/commit/94a233e0bacf60ae09d059f7ec58beb8fbf41bbe). Currently being worked on with https://github.com/getnamo/socketio-client-ue4/tree/issue-126 branch. Should do more thorough tests when it's merged to dev-unstable.

**Comment by getnamo** [comment]
According to https://github.com/getnamo/socketio-client-ue4/issues/156 there is still an issue
