### ISSUE TITLE
Listen a String 

### ISSUE THREAD

**Issue by Sere1** [getnamo/socketio-client-ue4#131]
How can i receive a string with c++ from a server

**Comment by getnamo** [comment]
see https://github.com/getnamo/socketio-client-ue4#receiving-events the receiving object can then be converted via standard http://api.unrealengine.com/INT/API/Runtime/Json/Dom/FJsonValue/ ways e.g. ```AsString()```

**Comment by Sere1** [comment]
i didnt be convert :( i want to be print  the receiving object on screen as a string

**Comment by getnamo** [comment]
You can find an example of how to convert to json string here: https://github.com/getnamo/socketio-client-ue4#ustruct. The key part is to use ```USIOJConvert::ToJsonString()``` (declared in https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SIOJson/Public/SIOJConvert.h)

So an OnNativeEvent receiving version of this would look like:

```c++
SIOClientComponent->OnNativeEvent(FString("MyEvent"), [](const FString& Event, const TSharedPtr<FJsonValue>& Message)
{
	//Show what we received
	UE_LOG(LogTemp, Log, TEXT("Received a response: %s"), *USIOJConvert::ToJsonString(Message));
});
```

**Comment by getnamo** [comment]
updated https://github.com/getnamo/socketio-client-ue4/blob/master/README.md#receiving-events to have the log example
