### ISSUE TITLE
Plugin making all Blueprint Nodes undefined (custom source build)

### ISSUE THREAD

**Issue by RandolphAarseth** [getnamo/socketio-client-ue4#133]
Everytime I start my project up, the blueprint nodes simply disconnect from everythiung and give me errors.

> LogLinker: Warning: Can't find file '/Script/SocketIOClient'
LogLinker: Warning: Can't find file for asset '/Script/SocketIOClient' while loading NULL.
LogLinker: Warning: Can't find file '/Script/SocketIOClient'
LogLinker: Warning: Can't find file for asset '/Script/SocketIOClient' while loading NULL.
LogLinker: Warning: Can't find file '/Script/SocketIOClient'
LogLinker: Warning: Can't find file for asset '/Script/SocketIOClient' while loading NULL.
LogLinker: Warning: Unable to load SocketIOClient_GEN_VARIABLE with outer BlueprintGeneratedClass /Game/FirstPerson/Demo/WebSocket.WebSocket_C because its class does not exist
LogLinker: Warning: Can't find file '/Script/SocketIOClient'
LogLinker: Warning: Can't find file for asset '/Script/SocketIOClient' while loading NULL.
LogLinker: Warning: Can't find file '/Script/SocketIOClient'
LogLinker: Warning: Can't find file for asset '/Script/SocketIOClient' while loading NULL.
LogLinker: Warning: Can't find file '/Script/SocketIOClient'
LoadErrors: Failed to load /Script/SocketIOClient.SocketIOClientComponent Referenced by SCS_Node_1
LogLinker: Warning: Can't find file for asset '/Script/SocketIOClient' while loading NULL.
LogLinker: Warning: Can't find file '/Script/SocketIOClient'
LoadErrors: Failed to load /Script/SocketIOClient.SocketIOClientComponent Referenced by K2Node_ComponentBoundEvent_0
LogLinker: Warning: Can't find file for asset '/Script/SocketIOClient' while loading NULL.
LogLinker: Warning: Can't find file '/Script/SocketIOClient'
LoadErrors: Failed to load /Script/SocketIOClient Referenced by K2Node_ComponentBoundEvent_0
LogLinker: Warning: Can't find file for asset '/Script/SocketIOClient' while loading NULL.
LogBlueprint: Warning: Repaired invalid component bound event in node /Game/FirstPerson/Demo/WebSocket.WebSocket:EventGraph.K2Node_ComponentBoundEvent_0.
LogLinker: Warning: Can't find file '/Script/SocketIOClient'
LoadErrors: Failed to load /Script/SocketIOClient.SocketIOClientComponent Referenced by K2Node_VariableGet_4
LogLinker: Warning: Can't find file for asset '/Script/SocketIOClient' while loading NULL.
LogLinker: Warning: Can't find file '/Script/SocketIOClient'
LoadErrors: Failed to load /Script/SocketIOClient.SocketIOClientComponent Referenced by K2Node_CallFunction_0
LogLinker: Warning: Can't find file for asset '/Script/SocketIOClient' while loading NULL.
LogLinker: Warning: Can't find file '/Script/SocketIOClient'
LoadErrors: Failed to load /Script/SocketIOClient.SocketIOClientComponent Referenced by K2Node_CallFunction_0
LogLinker: Warning: Can't find file for asset '/Script/SocketIOClient' while loading NULL.
LogBlueprint: Warning: [Compiler WebSocket] Component class is not set for 'SocketIOClient' - this component will not be instanced, and additional warnings or errors may occur when compiling Blueprint 'WebSocket'.
LogBlueprint: Error: [Compiler WebSocket] In use pin  Event  no longer exists on node  On Event (SocketIOClient) . Please refresh node or break links to remove pin.
LogBlueprint: Error: [Compiler WebSocket] In use pin  MessageJson  no longer exists on node  On Event (SocketIOClient) . Please refresh node or break links to remove pin.
LogBlueprint: Warning: [Compiler WebSocket] [0005.02] Compile of WebSocket failed. 2 Fatal Issue(s) 1 Warning(s) [in 12 ms] (/Game/FirstPerson/Demo/WebSocket.WebSocket)
LogLinker: Warning: Can't find file '/Script/SocketIOClient'
LogLinker: Warning: Can't find file for asset '/Script/SocketIOClient' while loading NULL.
LogLinker: Warning: Can't find file '/Script/SocketIOClient'
LogLinker: Warning: Can't find file for asset '/Script/SocketIOClient' while loading NULL.

**Comment by getnamo** [comment]
Looks like you've disabled the plugin? It doesn't seem to find the assets

**Comment by RandolphAarseth** [comment]
no it is enabled, I do all the development in it, then when I close the project and restart it, it simply gives me that error disconnects all the blueprint nodes, and makes everything undefined.

I did however fix the issue by switching to another project completely that wasn't build from source.

Originally this issue was specifically happening on 4.22.3 built from source.
But does not happen on a new project launched from the Epic Games Launcher's Installation of 4.22.3

I did replicate the issue by creating a empty project generated from the UE4.22.3 built from source and it did the same issue.

Not sure if its with that source build or not.

**Comment by getnamo** [comment]
try removing "EngineVersion" from https://github.com/getnamo/socketio-client-ue4/blob/master/SocketIOClient.uplugin for custom source builds. It might not get included in a build otherwise?

**Comment by sinper0079** [comment]
I have the same issue too, I have removed engine version. It still have the same problem.

**Comment by sinper0079** [comment]
I solved the problem by setting 			"LoadingPhase": "PreDefault",

**Comment by getnamo** [comment]
That would make sense if another plugin that depends on it uses predefault or default loading phase.

**Comment by DawidBujak** [comment]
sinper0079 - thanks
