### ISSUE TITLE
SocketIOComponent or FSocketIONative in GameInstance

### ISSUE THREAD

**Issue by dobby5** [getnamo/socketio-client-ue4#134]
Hello,

I tried to integrate the SocketIOComponent into the GameInstance and also tried the FSocketIONative.

Can someone please help me include this in the code?

Thx

**Comment by getnamo** [comment]
see https://github.com/getnamo/socketio-client-ue4/issues/138. Static construct support support has been added. Example game instance C++: https://github.com/getnamo/socketio-client-ue4/blob//README.md#example-fsocketionative-custom-game-instance

**Comment by dobby5** [comment]
It works thx.
