### ISSUE TITLE
AsObject

### ISSUE THREAD

**Issue by Sere1** [getnamo/socketio-client-ue4#137]
i want to  decode FJsonValue into a FJsonObject. How can i use AsObject() ?

**Comment by getnamo** [comment]
Assuming you have e.g.
```TSharedPtr<FJsonValue> MyValue;```

then you can convert it to an object via

```TSharedPtr<FJsonObject> MyObject = MyValue->AsObject();```

if you don't want to write the types this is also valid

```auto MyObject = MyValue->AsObject();```

Note that if this is an emit callback, the signature is a JsonValue array e.g.

```const TArray<TSharedPtr<FJsonValue>>& ResponseArray```

you can then get the first value as an object via e.g.

```auto ResponseObject = ResponseArray[0]->AsObject();```

See https://api.unrealengine.com/INT/API/Runtime/Json/Dom/FJsonValue/index.html for details.
