### ISSUE TITLE
SIOJson Link Errors

### ISSUE THREAD

**Issue by abreu20011** [getnamo/socketio-client-ue4#139]
Inside Build.cs I added:
modules.Add("SIOJson");

Inside Plugins folder, I have:
Plugins/socketio-client-ue4/Binaries/Win64/UE4Editor-SIOJson.dll
and:
Plugins/socketio-client-ue4/Source/SIOJson/Public/SIOJLibrary.h

and from 0001 to 0011 DLL files:
Plugins/socketio-client-ue4/Binaries/Win64/UE4Editor-SIOJson-0001.dll
.
Plugins/socketio-client-ue4/Binaries/Win64/UE4Editor-SIOJson-0011.dll

And, in source code I have:

#include "SIOJson/Public/SIOJLibrary.h"
void foo(){
    USIOJLibrary::Base64Encode("Hola");
}

However, If I call any function from USIOJLibrary I get a LINK Error:

error LNK2019: unresolved external symbol "public: static class FString __cdecl USIOJLibrary::Base64Encode(class FString const &)" (?Base64Encode@USIOJLibrary@@SA?AVFString@@AEBV2@@Z) referenced in function "public: void __cdecl ASocketListener::SendConfiguration(struct FMakeConfigRoot const &)" (?SendConfiguration@ASocketListener@@QEAAXAEBUFMakeConfigRoot@@@Z)
2>D:\Documents\unreal\IvrProject\Binaries\Win64\UE4Editor-IvrProject-0005.dll : fatal error LNK1120: 1 unresolved externals

**Comment by getnamo** [comment]
Hmm USIOJLibrary isn't module exposed (seems like you're the first one to use it in C++).

change https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SIOJson/Public/SIOJLibrary.h#L47 to read

``` class SIOJSON_API USIOJLibrary : public UBlueprintFunctionLibrary ```

and let me know if that fixes it.

**Comment by getnamo** [comment]
potential fix https://github.com/getnamo/socketio-client-ue4/commit/dc049690afc48f960550507ba2be2793b9133f99

**Comment by abreu20011** [comment]
It works! :) 
Thanks so much!! ♥
