### ISSUE TITLE
Editor Only Connection

### ISSUE THREAD

**Issue by gitumar** [getnamo/socketio-client-ue4#144]
Great Plugin!

Is there a way one can get the socket io ue4 client to work without actually "running" a game? For example, could we get a client running in a Editor Utility Widget for say an in editor chat box. I tried and failed. I also tried to put the blueprint logic inside the construction script of a BP actor and it just crashes. Everything works flawlessly in side a BP actor with game actually running. Thanks

**Comment by getnamo** [comment]
You'll likely need to use C++ with [FSocketIONative](https://github.com/getnamo/socketio-client-ue4#c-fsocketionative) to use in editor only context.

**Comment by KarthikHebbarMN** [comment]
@gitumar Were you able to get it to work ?
Just getting started with Editor scripting with c++ for Unreal.  I tried and got header missing issues. 
Any reference repo or example would be great. 

Thanks
