### ISSUE TITLE
OnEvent is never triggered

### ISSUE THREAD

**Issue by kvonflotow** [getnamo/socketio-client-ue4#148]
It connects fine - I can see the connection happen in Unreal (4.22.3) and on the socketio server (2.2.0), and my socketio server tells me it's sending events to the client, but OnEvent is never triggered. I was able to send events to the server just fine. I'm afraid I don't have a lot more info than that and since the deadline is really short I don't have time to deal with troubleshooting, so I'm moving onto a different option. Just wanted to let this be known... I've tried the 1.0.0 and 1.1.0e releases and both have the same issue. It's all running locally atm.

Thought this would be easy, but alas... nothing is easy ;)

**Comment by getnamo** [comment]
Did you bind the events before trying to receive them? (https://github.com/getnamo/socketio-client-ue4#how-to-use---bp-basics)

**Comment by kvonflotow** [comment]
I did not, and now I feel like a dummy :) I guess I missed that part - I expected it to receive automatically.

Will put it back together real quick and make sure that's where I messed up, but I'm assuming you're right.

**Comment by kvonflotow** [comment]
Confirmed that I just needed to bind the events
