### ISSUE TITLE
android connection impossible

### ISSUE THREAD

**Issue by xernois** [getnamo/socketio-client-ue4#151]
After packaging / launching the game for Android, the device does not connect to the sockets (Works on PC), is there something to do to fix it ?

**Comment by getnamo** [comment]
plugin and unreal version, server type (http/https?) etc?

**Comment by xernois** [comment]
The version of unreal is 4.22 and the plugin version is 1.0.0, the server is an http one (node.Js) , I can send you the server code if you want to see it!

**Comment by xernois** [comment]
@getnamo Any idea of what is wrong?

**Comment by getnamo** [comment]
Will likely need to see your blueprints to see what you might be doing differently. Are you packaging with a minimum target of 21 or newer? (https://github.com/getnamo/socketio-client-ue4#android)

**Comment by xernois** [comment]
We are binding the event, using the On event function it works on the PC Editor but when we build the app or launch it on android the server doesn't detect any connection frome the app and the app doesn't get any event, it's weird and we are packaging above target 21

**Comment by xernois** [comment]
Did you need to see blueprints?

**Comment by getnamo** [comment]
Sanity check: you're not using localhost e.g. http://localhost:3000 as connecting url on android right? You'd need them to be on the same network (if using test server on e.g. desktop/laptop) or use external ip/domain for the android to connect.

**Comment by xernois** [comment]
Nope, I've set my port forwarding like it needs to be and I'm not not using the local ip ?
![unknown](https://user-images.githubusercontent.com/32645608/64201066-5795f980-cec0-11e9-9d21-013f11356e49.png)

**Comment by xernois** [comment]
We tried with our local ip and the android device on the same wifi network and this error keeps happening `SocketIOLog: SocketIO Invalid appears to have lost connection, reconnecting attempt 31 with delay 25000`

**Comment by getnamo** [comment]
That does seem like it doesn't ever reach, can you confirm your server is reachable via e.g. tcp with the same setup? (try something like https://github.com/getnamo/tcp-ue4 and https://gist.github.com/getnamo/7350f00823f46d9463240160320d03a3 for an easy test)

**Comment by xernois** [comment]
ok i will try this tomorrow, i keep you in touch !
Thx for your help.

**Comment by xernois** [comment]
@getnamo ,we  tried with https://gist.github.com/getnamo/7350f00823f46d9463240160320d03a3  as server with port 3000 and the tcp plugin (https://github.com/getnamo/tcp-ue4) and it's working on pc Editor but as soon as i launch it on an android device it doesnt connect ! 
And in the log console  this error keeps happening :
![b](https://user-images.githubusercontent.com/32645608/64253445-e867e600-cf4f-11e9-9ad2-111239b5baa5.png)
but the tcp component is set properly :
![a](https://user-images.githubusercontent.com/32645608/64253594-2d8c1800-cf50-11e9-8839-8e32fea751a1.png)
We also tried to use the plugin function :  `connect` .

**Comment by xernois** [comment]
@getnamo, We found out that each time we were compiling the game, anything related to the plugin wouldn't work, even on PC now.

**Comment by getnamo** [comment]
If tcp can't connect to your server then it points to some server config problems (firewall blocking incoming connection?, ports aren't forwarded? try e.g. https://check-host.net/?lang=en to help debug setup)

**Comment by xernois** [comment]
@getnamo, ```I tried with the website https://check-host.net/ and it return me this :

[unknown](https://user-images.githubusercontent.com/32645608/64289959-78645a80-cf65-11e9-9ed9-49db074a9589.png)

So I guess the server is OK cause I also tried with a friend to use my ip and so my server and for him it's the same, it works on pc editor but it's not working after building for windows or for Android, so truly sorry to ask you that but are you sure that there is no issue with your plugin after building cause it doesn't seem like it's coming from us cause everything else in the project is fine ?! ```

**Comment by getnamo** [comment]
I haven't seen packaging problems of this type before. Can you confirm the issue remains with the early release https://github.com/getnamo/socketio-client-ue4/releases/tag/v1.1.0e(1.0.24)? If so can you please share screenshot of Project Settings->(Platforms)Android and Project Settings->(Platforms)Android SDK

Here are mine for reference:
![image](https://user-images.githubusercontent.com/542365/64333328-29c9b700-cf8b-11e9-9f04-d89553b8c641.png)

![image](https://user-images.githubusercontent.com/542365/64333372-3a7a2d00-cf8b-11e9-82ba-9a6366fe4440.png)

So far I've had success with NDK toolchain r14b, Minimum and Target SDK 21, and packaging ASTC for either armv7 or arm64

Just tested armv7 with 1.0.24 build
![image](https://user-images.githubusercontent.com/542365/64333409-4b2aa300-cf8b-11e9-8713-c212c9fbd9ed.png)

with my IP set to my local network address (192.168...) where my node.js server is running on my pc. Seemed to work without issue. I wonder if a local proxy/forwarder on your server might be the source of the issue.

**Comment by xernois** [comment]
Ok thanks I will try this out in a few hours

**Comment by xernois** [comment]
@getnamo,I tried with your with and your own node.js server. During the build an error occured and the error showed up again on my project, it's that one : 

![Capture](https://user-images.githubusercontent.com/32645608/64364129-d9169480-d044-11e9-84ab-dbffdc1bffae.PNG)

**Comment by getnamo** [comment]
Sanity check did you follow this: https://github.com/getnamo/socketio-client-ue4#github? Convert bp only project to mixed.

Without it, it will still often show a successful package but it will not include the c++ compilation stage of the plugin hence nothing will work.

This step isn't required if you are using the marketplace version of the plugin (because it's pre-built and placed in the engine folder)

**Comment by xernois** [comment]
Thanks to you it work perfectly !!
