### ISSUE TITLE
Win32 build failed

### ISSUE THREAD

**Issue by Wadimich** [getnamo/socketio-client-ue4#155]
I have to add `defined(__GNUC__)` to files

> SocketIOClient\Source\ThirdParty\rapidjson\include\rapidjson\internal\diyfp.h:78
> SocketIOClient\Source\ThirdParty\rapidjson\include\rapidjson\internal\biginteger.h:255

To make build work, but i am not sure this is great. Please check it.

**Comment by getnamo** [comment]
I did a very similar fix, the changes are in the v1.0.24 release and master branch: https://github.com/getnamo/socketio-client-ue4/commit/b6ffc66728b42caa8d59344c9ebe49e02f443dc9
