### ISSUE TITLE
The network disconnects when too much data is sent at once

### ISSUE THREAD

**Issue by lwglwg** [getnamo/socketio-client-ue4#156]
The network disconnects when too much data is sent at once,For example, 200 KB,Can the data transferred be set

**Comment by lwglwg** [comment]
send 100kb it work,but send 200KB, tried many times,It happens every time,This is a log
LogTemp: Pong timeout => closing connection with 0
LogTemp: Close by reason: Pong timeout

**Comment by getnamo** [comment]
Have you tried the latest early release https://github.com/getnamo/socketio-client-ue4/releases/tag/v1.1.0e(1.0.24), does it still happen in this version?

**Comment by getnamo** [comment]
Issue is duplicate of https://github.com/getnamo/socketio-client-ue4/issues/130

**Comment by lwglwg** [comment]
i tried the  https://github.com/getnamo/socketio-client-ue4/releases/tag/v1.1.0e(1.0.24)，The question remains

**Comment by getnamo** [comment]
Ok I'll investigate larger packet problems in 1.0.24, will continue the discussion on the issue at #130, closing the duplicate here
