### ISSUE TITLE
 v1.1.0e(1.0.24) ios build failed

### ISSUE THREAD

**Issue by lwglwg** [getnamo/socketio-client-ue4#157]
v1.1.0e(1.0.24) ios build failed! but android build success!

**Comment by getnamo** [comment]
Interesting, do you have a build log you can share for ios?

**Comment by lwglwg** [comment]
<img width="1663" alt="bug" src="https://user-images.githubusercontent.com/5474809/64697778-2cb93000-d4d4-11e9-814c-39ae990fbd71.png">

**Comment by getnamo** [comment]
re-pull master or use https://github.com/getnamo/socketio-client-ue4/releases/tag/1.2.0 and re-open if issue persists
