### ISSUE TITLE
socket location in multiplayer games

### ISSUE THREAD

**Issue by Nestoro** [getnamo/socketio-client-ue4#158]
Hello,
i have an issue with the usability of this plugin for multiplayer games that rely on unreal engine sessions to connect players and use this plugin to communicate with an dedicated server.

my intended use is that i join a multiplayer session and each player has his own connection to the dedicated server to hide sensitive data from each other and produce a peer to peer/dedicated server hybrid.
i drew this graphic to further explain my intended behavior:
![graphic](https://user-images.githubusercontent.com/13397845/65087951-e83c0180-d9b7-11e9-9a6f-08e75ea13847.png)

the problem i encountered is that the sockets get duplicated on each client because other clients also call the on start event on the character blueprint which initiates the socket and binds the responses to it. this way i have multiple unused / error producing connections with my node server which cause problems with the game flow.

i have no problem with socket.io itself i just need to find a way to get this system to work without making it full dedicated server based or removing the dedicated server aspect.

if you want to reproduce this you need 
1. a server for socket.io
2. a unreal engine multiplayer ready game. (i would recommend using the third-person template to begin with) You can follow this documentation to achieve this [https://docs.unrealengine.com/en-US/Programming/Online/SessionInterface/index.html](url)
3. and then add the socket and some connection requests to character blueprint
now you should be able to see with each joining player a increasing number of request, because every time a new player joins all already connected players also use his socket.

hope someone can help me finding our how to implement the desired behavior without changing the structure to much.

~Nestoro

**Comment by getnamo** [comment]
I think I understand what might be the issue: each time a player joins on the unreal network a character is spawned on every unreal network connected client and on the server. If you have a socket.io component attached to the character class with auto connection on, each of these remote duplicates of your character socket.io clients will try to connect.

What you need to do is turn off auto-connect on the socket.io component and only connect if your character has authority. See https://docs.unrealengine.com/en-US/Resources/ContentExamples/Networking/1_2/index.html. 

e.g. maybe something like this

![image](https://user-images.githubusercontent.com/542365/65111677-d0ea1d80-d991-11e9-9439-fbf61856f0a1.png)

**Comment by Nestoro** [comment]
Yes,
i had auto-connect already off because i used dynamic urls based on session properties.

the hasAuthority switch almost works as intended but limits the connections to be called just from the host. 
i filter for local player now and it seems to be working like a charm thank you for the inspiration!
