### ISSUE TITLE
Error : Enumeration tag 'GET' already in use by enum '/Script/SIOJson.ERequestVerb'

### ISSUE THREAD

**Issue by Tauri4n** [getnamo/socketio-client-ue4#16]
Hello, when compiling with 4.14 source, I get the following error:
`error : Enumeration tag 'GET' already in use by enum '/Script/SIOJson.ERequestVerb'`

There seems to be some kind of conflict with VaRest (v1.1-r16).

Any idea what the problem could be?

**Comment by getnamo** [comment]
Yep that is likely. Found all the enums that might have a conflict https://github.com/getnamo/socketio-client-ue4/commit/3dd58071967c8fbe4721aa5550a7cd23d7e5b298, made a merge so let me know if the latest master has this issue fixed.

**Comment by Tauri4n** [comment]
Works great -- Thanks.
