### ISSUE TITLE
First connection to heroku based socketIo server crashes the ue4 client

### ISSUE THREAD

**Issue by uetopia** [getnamo/socketio-client-ue4#160]
My first connection attempt in a work session will crash with the following:

[2019.09.24-14.18.46:684][840]LogTemp: [UETOPIA] IdentityInterface->SocketExternalIpSet
[2019.09.24-14.18.46:684][840]LogTemp: SocketIO AddressAndPort: http://uetopia.herokuapp.com
[2019.09.24-14.18.46:684][840]LogOnline: Display: UETOPIA: FOnlineSubsystemUEtopia::Connect
[2019.09.24-14.18.46:684][840]LogOnline: Display: UETOPIA: FOnlineSubsystemUEtopia::Connect !bPluginScopedConnection
[2019.09.24-14.18.46:687][840]LogOnline: Display: UETOPIA: FOnlineSubsystemUEtopia::SetupCallbacks
[2019.09.24-14.18.46:687][840]LogOnline: Display: UETOPIA: FOnlineSubsystemUEtopia::Connect NativeClient->connect
[2019.09.24-14.18.46:687][840]LogOnline: Display: UETOPIA: FOnlineSubsystemUEtopia::ConnectNative
Assertion failed: FMallocBinned2::FPoolInfo::IsSupportedSize(Size) [File:C:/UE423_uetopia_test/Engine/Source/Runtime/Core/Private/HAL/MallocBinned2.cpp] [Line: 788]

Aall other consecutive connections work correctly.  Quitting the ue4 client, and relaunching it also works.

I am assuming there is some latency or something with the heroku server starting up that is causing a failure.

Did something change in the latest version related to this?  Is this the correct diagnosis?  Is there a timeout that I should increase somewhere to allow for this startup time?

Server is Node, running socketIO 1.4.6
SocketIo Plugin is version 1.1.10
Engine Version is 4.23

**Comment by getnamo** [comment]
Do you have a few lines of code near the crash to show? Hard to diagnose without knowing when the connection call is called with what params

**Comment by uetopia** [comment]
Here is my connect function

`std::string StdAddressString = USIOMessageConvertUEtopia::StdString(InAddressAndPort);
	if (InAddressAndPort.IsEmpty())
	{
		UE_LOG_ONLINE(Display, TEXT("FOnlineSubsystemUEtopia::Connect InAddressAndPort.IsEmpty()"));
		StdAddressString = USIOMessageConvertUEtopia::StdString(AddressAndPort);
	}

	//Because our connections can last longer than game world
		//end, we let plugin-scoped structures manage our memory
	if (bPluginScopedConnection)
	{
		UE_LOG_ONLINE(Display, TEXT("FOnlineSubsystemUEtopia::Connect bPluginScopedConnection"));
		NativeClient = ISocketIOClientModule::Get().ValidSharedNativePointer(PluginScopedId);
	}
	else
	{
		UE_LOG_ONLINE(Display, TEXT("FOnlineSubsystemUEtopia::Connect !bPluginScopedConnection"));
		NativeClient = ISocketIOClientModule::Get().NewValidNativePointer();
	}

	SetupCallbacks();

	const USIOJsonObject* SafeQuery = Query;
	const USIOJsonObject* SafeHeaders = Headers;

	TSharedPtr<FJsonObject> QueryFJson;
	TSharedPtr<FJsonObject> HeadersFJson;

	if (Query != nullptr)
	{
		QueryFJson = Query->GetRootObject();
	}

	if (Headers != nullptr)
	{
		HeadersFJson = Headers->GetRootObject();
	}

	UE_LOG_ONLINE(Display, TEXT("FOnlineSubsystemUEtopia::Connect NativeClient->connect"));


	//Ensure we sync our native max/reconnection attempts before connecting
	NativeClient->MaxReconnectionAttempts = MaxReconnectionAttempts;
	NativeClient->ReconnectionDelay = ReconnectionDelayInMs;
	NativeClient->VerboseLog = bVerboseConnectionLog;

	ConnectNative(InAddressAndPort, QueryFJson, HeadersFJson);`

**Comment by uetopia** [comment]
and related settings from Init:

// socketIO stuff
	bShouldAutoConnect = true;
	//bWantsInitializeComponent = true;
	//bAutoActivate = true;
	//ConnectionThread = nullptr;
	NativeClient = nullptr;
	AddressAndPort = FString(TEXT("http://localhost:3000"));	//default to 127.0.0.1
	SessionId = FString(TEXT("invalid"));
	//PrivateClient = new sio::client;

	//Plugin scoped utilities
	bPluginScopedConnection = false;
	PluginScopedId = TEXT("Default");
	bVerboseConnectionLog = true;
	ReconnectionTimeout = 0.f;
	MaxReconnectionAttempts = -1.f;
	ReconnectionDelayInMs = 5000;

	ClearCallbacks();

**Comment by getnamo** [comment]
Interesting, everything looks normal so far. Do you have a .dmp file (check
logs folder) from the crash? I think I need to see the stack crashing it

**Comment by Lirrec** [comment]
I had the same issue today.
I think i found a potential cause for this.
In my case the crash itself only appears sporadically, i believe it to be a reference to a local variable being undeclared in the connect lamba.

The local variable StdAddressString from here:
https://github.com/getnamo/socketio-client-ue4/blob/763a855af49a426822c9b832a6604fb78c72eba8/Source/SocketIOClient/Private/SocketIONative.cpp#L30

is used by reference in the lambda here:
https://github.com/getnamo/socketio-client-ue4/blob/763a855af49a426822c9b832a6604fb78c72eba8/Source/SocketIOClient/Private/SocketIONative.cpp#L37

and used in the further call:
https://github.com/getnamo/socketio-client-ue4/blob/763a855af49a426822c9b832a6604fb78c72eba8/Source/SocketIOClient/Private/SocketIONative.cpp#L60

And finally contains garbage later on as can be seen in the debugger:
![socketio_connect_issue](https://user-images.githubusercontent.com/2570469/65597421-62145200-df99-11e9-97ed-c556c221cca1.png)

Bugfix should be replacing `FCULambdaRunnable::RunLambdaOnBackGroundThread([&, Query, Headers] ` with `FCULambdaRunnable::RunLambdaOnBackGroundThread([&, StdAddressString, Query, Headers] `.

**Comment by getnamo** [comment]
You are correct, we should be capturing that by value. If you want to open a pull request (on dev-unstable), I'll merge it or I can add the fix myself.

**Comment by getnamo** [comment]
I went ahead and merged a fix here: https://github.com/getnamo/socketio-client-ue4/commit/cf65cd80c5fbb6de02de8c0cec7507799b21fad3 from issue-160 branch. Also updated the connection logic while I was there to support reconnecting by just passing a new address to connect: https://github.com/getnamo/socketio-client-ue4/commit/f117093daf2e5b9c011d9f40d6831a3964635663

**Comment by uetopia** [comment]
First connection worked.  Since it was an intermittent issue, I will report back after more testing.  Thanks @getnamo and @Lirrec

**Comment by getnamo** [comment]
Closing, re-open if issue comes back
