### ISSUE TITLE
Win64 debug build failed

### ISSUE THREAD

**Issue by Wadimich** [getnamo/socketio-client-ue4#167]
UE 4.23.1 from source
Socket IO Client 1.2.4 (latest upon writing this issue)

When compiling sources UE drops 2 errors

```
socketioclient\source\thirdparty\rapidjson\include\rapidjson\internal\biginteger.h(255): error C4668: '__GNUC__' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
socketioclient\source\thirdparty\rapidjson\include\rapidjson\internal\diyfp.h(78): error C4668: '__GNUC__' is not defined as a preprocessor macro, replacing with '0' for '#if/#elif'
```

**Comment by getnamo** [comment]
for which platform?

**Comment by Wadimich** [comment]
It seems, i had old submodules, now it is fixed. Thank you!

_I'm curious about, how it worked without new versions, there is a very big diff after update_

**Comment by getnamo** [comment]
Glad that worked! Regarding why it worked before pull, I suspect that's due to socket.io lib api <-> third party modules being fairly static for a while now. Main diffs in submodules have been mostly upstream updates and fixing some new bugs that crept up in the updates, such as polling timeouts.
