### ISSUE TITLE
SIOJLibrary crashing when working with Byte 

### ISSUE THREAD

**Issue by Arziel** [getnamo/socketio-client-ue4#168]
Hello, 
after migrate from 4.21 to 4.23 my code start crashing on blueprint node `Struct to Json Object`. After some debugging i got where problem it is. 

It's throws exception when the struct contains `Byte` attribute. 

Can it be fixed?

TY for nice plugins. :]]

**Comment by getnamo** [comment]
Do you have a log and/or some blueprint c++ code that leads up to the crash?

**Comment by Arziel** [comment]
@getnamo 

Yeah, i prepare a sandbox repo with replicated bug.  https://github.com/Arziel/ue4-sioj-byte-bug 

Just run a game in editor and it should failed like described on top. When u look at logs, u can see that structure without `Byte` was build as normal, but when code execute part with `Byte` struct throws uncaughted exception.

**Comment by getnamo** [comment]
Preliminary fix: https://github.com/getnamo/socketio-client-ue4/commit/16b0d59edc37c1f324f11f4087efd1cb80ad4ef1. This adds support for UStruct->json with byte (converted to ints) and byte array (converted to FJsonBinaryValues) field types. Keep in mind that if you are using socket.io that you shouldn't encode object to string but send the SIOJsonValue(SIOJsonObject) instead. The internal protocol will serialize as per sio spec with binary interwoven objects (optimal bandwidth overhead).

That said I'm now working on supporting the reverse backup option json string->byte array woven inside a struct. This will enable bi-directional fallback if you're not using the socket.io stream (maybe you're pushing the json as http requests or something that doesn't support binary interweaving). Tracked here: (https://github.com/getnamo/socketio-client-ue4/issues/169)
