### ISSUE TITLE
Is there a way to run the "On Event" event on a separate thread?

### ISSUE THREAD

**Issue by sleoniy** [getnamo/socketio-client-ue4#172]
Hey Getnamo, cant stress how much I appreciate your work. Just have a question in regards to receiving events on a separate thread. I am using socketio to continuously pull in data from a stream. I noticed that when I try to transmit 100,000 records, the delay increases over time and the game thread is blocked until all events are received. I was wondering if you could guide me in the right direction so I can receive events without blocking game thread. Tysm! Currently am on UE 4.20 and SocketIO 0.95. I plan on upgrading soon but any help is appreciated.

EDIT: I know that SocketIO supports Blueprint multithreading, but specifically I need to receive events on a separate thread than Game Thread. Thanks!

**Comment by getnamo** [comment]
This is supported in v1.1.0 version of the plugin: https://github.com/getnamo/socketio-client-ue4/releases/tag/1.1.0

Using bind event to function, you can specify a thread override which has 3 options. Default (per socket.io component, typically game thread), game thread, and network thread. Setting the override to network thread should accomplish what you're looking for.

![image](https://user-images.githubusercontent.com/542365/69472108-f95c1280-0d5a-11ea-9667-579b22d77ac3.png)

The cool part about this setup is that you can decide on a per bound event which thread you wish to receive the message, keeping other unsafe events e.g. on game thread. 

NB: you cannot make or destroy uobjects on non-gamethreads and be mindful of your access patterns across threads to ensure you don't get a race condition.

**Comment by getnamo** [comment]
Added small section with same info to the readme: https://github.com/getnamo/socketio-client-ue4/blob/master/README.md#receiving-events-on-non-game-thread

**Comment by sleoniy** [comment]
Wow, great! Thank you so much for the response as that is exactly what I have been doing. It has come to my attention though that when you end play before the task finishes, it crashes the whole editor. If this is the case, you might be able to just add an "End Thread" function where you can specify network thread and just call it on the "End Play" event.

In addition, for future reference, are you considering adding the functionality to generate an entirely new thread, aside from just Game & Network Thread?

Thanks again for your time!!
