### ISSUE TITLE
Does not work in Windows executable

### ISSUE THREAD

**Issue by RidgeBatty** [getnamo/socketio-client-ue4#177]
Everything works nicely when the editor is running, even when launching "standalone game" inside the editor. But when it's built and run as a Windows executable, nothing happens and the SocketIOClient component is not active (and cannot be activated). 

If all instances of SocketIOClient are removed from the project, so there is NO way it can work, it does make a connection to localhost:3000 (default). Obviously there is no way to control any behavior because the component is not added in the project. 

Otherwise I love the project but I'm at a complete loss here.

Unreal version: 4.22
Error message: no errors, no logs, no nothing

**Comment by getnamo** [comment]
github or marketplace build? did you follow: https://github.com/getnamo/socketio-client-ue4#packaging? specifically if it's a github build you need to convert project from bp only to mixed.

**Comment by RidgeBatty** [comment]
Ok my mistake, apparently I stopped reading at "works out of the box". Followed instructions, no idea what they do, but it works. Thanks mate!
