### ISSUE TITLE
What is the most optimal way to continuously stream data?

### ISSUE THREAD

**Issue by sleoniy** [getnamo/socketio-client-ue4#179]
Hey Getnamo,

Very appreciative of your work. Long story short, I want to continuously stream data to visualize in UE4. I noticed that when constantly sending data on the Network Thread the game crashed. I tried to implement a sleep function where every 10000 records, my web socket would wait 16ms to process the next frame. This added a little bit more life but eventually the game freezes. I was just wondering if you could provide any guidance on how I can stream data efficiently without the clients game freezing. 

I am receiving events & storing in an array when received.
As for visualizing, this is being done on game thread when a user uses keybinds to iterate through all the messages received.

Thank you for your help!

**Comment by getnamo** [comment]
To replicate this issue, what kind of bandwidth is causing this issue? (MB/s) also are you sending these records individually or in batches?

**Comment by sleoniy** [comment]
Hey Getnamo,

Ty for responding. Below is an example payload I am sending,

        Ask = 0
	Bid = 0
	Last = 0
	Code = SLEO
	Symbol = SLEO
	Date = 2019-12-10
	close = 0
	open = 0

Once received, I convert JSON object to struct and then store in an array.

Currently, I am sending these records individually. I know that UE can store up to 2,129,920 UObjects, so I do not think storing is causing the issue here.

I noticed that if I combine multiple payloads into one record, results are as expected. Since the record is now greater in size, it crashes with a lesser amount of messages compared to individual payloads being sent.

My theory is that because I am receiving so much data on the network thread, it is causing a block which results in a crash. I was trying to add a delay of 500ms for every 10,000 records to allow UE to process more frames but eventually it will crash. On average, I get to about 27,000 records received before UE has a fatal crash.

Let me know if you need more details.

**Comment by getnamo** [comment]
It does seem to be an amount problem. Definitely batching the records is better than sending lots of tiny messages, but will need to test these limits better with debug points to see what's really happening in these edge cases.

It's possible that UObject wrapping in blueprint might be a culprit (C++ uses FJsonObject which doesn't use UObject wrapping), but likely it could be other parts too.

Just to confirm you're trying to send ~10000 record every second or is it more than that?
