### ISSUE TITLE
Conflict with VaRest when building for linux

### ISSUE THREAD

**Issue by Aureliaar** [getnamo/socketio-client-ue4#183]
Building for Linux with both VaRest and Socketio-client-ue4 results in a clang error, for a double definition of ConstructJsonValue

> 
> clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
>     ld.lld.exe: error: duplicate symbol: ConstructJsonValue(UObject, TSharedPtr<FJsonValue, (ESPMode)0> const&)
>     >>> defined at VaRestJsonValue.cpp:70 (C:/workspace/Madball_2/XBalls/Plugins/VaRestPlugin/Source/VaRestPlugin/Private\VaRestJsonValue.cpp:70)
>     >>>            C:/workspace/Madball_2/XBalls/Plugins/VaRestPlugin/Intermediate/Build/Linux/B4D820EA/XballsServer/Development/VaRestPlugin/VaRestJsonValue.cpp.o:(ConstructJsonValue(UObject, TSharedPtr<FJsonValue, (ESPMode)0> const&))
>     >>> defined at SIOJsonValue.cpp:116 (C:\workspace\Madball_2\XBalls\Plugins\socketio-client-ue4\Source\SIOJson\Private\SIOJsonValue.cpp:116)
>     >>>            C:/workspace/Madball_2/XBalls/Plugins/socketio-client-ue4/Intermediate/Build/Linux/B4D820EA/XballsServer/Development/SIOJson/Module.SIOJson.cpp.o:(.text+0xCC00)

**Comment by getnamo** [comment]
Plugin & unreal version? Marketplace or github build? 

Error points to line https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SIOJson/Private/SIOJsonValue.cpp#L116 which doesn't seem the same as what you're seeing based on current master branch.

**Comment by Aureliaar** [comment]
UE4.22.3, Github 1.2 4.22 release, VaRest marketplace release for 4.22, sorry.

Going into either VaRest or SIO specified line and renaming the BP-exposed function to anything else is a workaround.
(Line for master is https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SIOJson/Private/SIOJsonValue.cpp#L133, UVaRestJsonValue* ConstructJsonValue [...])
The error is Linux-build specific, and doesn't seem to reproduce on any Windows\Android builds, although i couldn't test iOS.

**Comment by robknopf** [comment]
I've encountered the same issue on Lumin / UE4.23 / SIO (GitHub).  Renaming ConstructJsonValue avoids what appears to be a name collision.

**Comment by getnamo** [comment]
Fixed in: https://github.com/getnamo/socketio-client-ue4/commit/1c5e5bcf2c53be3b7fb7cb6bfc43e0918c0c0918

**Comment by getnamo** [comment]
released in https://github.com/getnamo/socketio-client-ue4/releases/tag/1.3.5
