### ISSUE TITLE
Unable to build 4.24.1 engine with plugin

### ISSUE THREAD

**Issue by dazre** [getnamo/socketio-client-ue4#184]
Plugin sources placed into ue-source\Engine\Plugins\Marketplace\SocketIOClient

```
1>Invalidating makefile for UE4Server (SocketIOClient.uplugin has been added)
1>D:\UnrealEngine-4.24.1-release\Engine\Plugins\Marketplace\SocketIOClient\Source\SocketIOLib\SocketIOLib.Build.cs : warning : Referenced directory 'D:\UnrealEngine-4.24.1-release\Engine\Plugins\Marketplace\SocketIOClient\Source\ThirdParty\asio\asio\include' does not exist.
1>D:\UnrealEngine-4.24.1-release\Engine\Plugins\Marketplace\SocketIOClient\Source\SocketIOLib\SocketIOLib.Build.cs : warning : Referenced directory 'D:\UnrealEngine-4.24.1-release\Engine\Plugins\Marketplace\SocketIOClient\Source\ThirdParty\rapidjson\include' does not exist.
1>UnrealBuildTool : error : Unable to instantiate module 'UnrealEd': Unable to instantiate UnrealEd module for non-editor targets.
1>                        (referenced via Target -> SIOJEditorPlugin.Build.cs -> AssetTools.Build.cs)
```

**Comment by getnamo** [comment]
If you're using git, you may need to pull with --recurse-submodules to pull the third-party sources. Otherwise the marketplace 4.24 version is currently submitted pending approval.

**Comment by dazre** [comment]
I'm using [release archive](https://github.com/getnamo/socketio-client-ue4/releases) which unpak to the ue-source\Engine\Plugins\Marketplace\SocketIOClient folder. As I can see archive contain all submodules.

**Comment by dazre** [comment]
I tried sources and pak with binaries (*.7z) and the result is the same.

**Comment by marwanhilmi** [comment]
I've run into the same issue when trying to cook / package the client as a standalone. The problem is the use of `DeveloperTool` in the .uplugin definition. Can't find any documentation on why / how this has changed but the correct value should be `Editor`. Switching to `Editor` works. Had the same issue with our own plugins.

This is the offending line: https://github.com/getnamo/socketio-client-ue4/blob/f682bcc51a16343f7200bad541353f1878c076eb/SocketIOClient.uplugin#L77

**Comment by getnamo** [comment]
That makes sense. With 4.24 the developer category was removed and I thought developer tool was the correct context for that one, but it seems editor is the correct upgrade path. Thanks @marwanhilmi for spotting the fix!

**Comment by dazre** [comment]
@marwanhilmi Thanks a lot. @getnamo  The latest release is built without errors.
