### ISSUE TITLE
How to unsubscribe Socket.io event from function?

### ISSUE THREAD

**Issue by Wadimich** [getnamo/socketio-client-ue4#189]
I've looking for blueprints and didn't found anything like ubsubscribe or unbind. Please help!

UE version 4.23
Plugin version somewhere from github for 4.23 (Not sure what last commit was)

**Comment by getnamo** [comment]
You might be right, in C++ its usually as simple as binding an event to a null function. A handy wrapper is found here for native: https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SocketIOClient/Public/SocketIONative.h#L369

But I don't see one on the component that is used in bps. I'll add this as an enhancement, should be a quick few lines

**Comment by Wadimich** [comment]
@getnamo can you make separate branch for 4.23 version with this fix? Or can you just say, what i should fill in your code, so i get this thing?

**Comment by getnamo** [comment]
added in https://github.com/getnamo/socketio-client-ue4/commit/f11cd5ba1d14bf29805f287214d00f81eb3957ec. The 4.24 version of plugin (which is what master tracks atm) compiles in 4.23 without issue so you should be able to pull the latest master a rebuild your project. You might just need to change https://github.com/getnamo/socketio-client-ue4/blob/master/SocketIOClient.uplugin engine version to 4.23 to stop warning spam on bootup

**Comment by Wadimich** [comment]
Ok, did test with new node, works like a charm! Thank you!
