### ISSUE TITLE
Game crashes when opening packaged project

### ISSUE THREAD

**Issue by angelhodar** [getnamo/socketio-client-ue4#191]
Hey i just tried your plugin to make some communication with my server, but when packaging it all the process goes nice until i try to open the generated .exe, which instantly crashes. I have checked its because of your plugin because if i remove the execution pin for it everything works fine.

Using the Editor it just works perfect, its only after packaging. Am i missing any config? I just added the Plugins folder to my project as you say in the README, and also checked that everything in the editor was cooked but it didnt solve the problem. Just try it by yourself, im using the 4.24.3

Open a third person template, add the component to the third person character and emit something on the beginplay. Then package the game for windows 64 and it should crash instantly.

Any ideas?

**Comment by getnamo** [comment]
Did you change your project to C++ so it includes the plugin in the compile? (step found here https://github.com/getnamo/socketio-client-ue4#github)

**Comment by angelhodar** [comment]
I just feel stupid at the moment dude... I didnt watch the README until the end, now it just works fine! I have bought it in the marketplace so you get some money for your excellent work. Im going to use this plugin for the Oculus Quest, are you aware of any possible errors or things to keep in mind while using the plugin to work on a standaole apk in the Quest?

Again, sorry for being stupid ):

**Comment by getnamo** [comment]
It's perfectly understandable, the readme for the plugin is pretty long, easy to miss. This is why there are issues for questions; thanks for the support :).

Regarding the Quest, I use it myself for the quest and it works as expected when packaged.

Keep in mind that if you're using the default option in BPs where you get the networking data callbacks on the game threads, you can run into limitations on throughput (you'd need ~1000+ messages/sec or really large files to hit this). If that's the case consider: https://github.com/getnamo/socketio-client-ue4#receiving-events-on-non-game-thread or dropping down to the C++ [FSocketIONative](https://github.com/getnamo/socketio-client-ue4#c-fsocketionative) which can process the data on a background thread to keep everything smooth. I wouldn't pursue these options until you hit limitations though.
