### ISSUE TITLE
Event "On" doesn't work

### ISSUE THREAD

**Issue by Pietro228** [getnamo/socketio-client-ue4#192]
Hi,

when I want to get reply from server, it will not work because the event "On" doesn't work. Emits and other things work except this. I tried to use debuging but it doesn't execute.

![Event Graph 17 03 2020 8_37_12](https://user-images.githubusercontent.com/53868994/76832872-822b1c80-682a-11ea-965d-a7d15b914238.png)

Regards,
Peter

**Comment by getnamo** [comment]
You need to bind your event before you can receive it, see https://github.com/getnamo/socketio-client-ue4#how-to-use---bp-basics
