### ISSUE TITLE
How do I make the unreal socket.io client work on custom path?

### ISSUE THREAD

**Issue by Spejik** [getnamo/socketio-client-ue4#193]
When I create a socket.io server with 
`const io: socket.Server = socket.listen(httpServer, { path: "/game_sockets/socket.io" });`
It works in the browser, but when I try connecting to it in unreal (with "http://our-server-ip-adress:80/game_sockets/socket.io"), it doesn't do anything.
I've also created an express middleware that logs all requests, but it seems like unreal doesn't even send them.

**Comment by getnamo** [comment]
Hmm not sure, it should in theory work out of the box, but I guess something is missing. Marking this as a bug until I can replicate it.

**Comment by brittanft** [comment]
@Spejik You have to manually edit the SocketIO plugin files. Copy all the steps in this commit: https://github.com/ahmetalperenbulut/socket.io-client-cpp/commit/c9315ac317c9dba54a87c7493a3d2ac56c822afc

Then add support for the new argument by modifying or making new connect functions in the SocketIOClientComponent and SocketIONative files.

**Comment by getnamo** [comment]
If you make a pull request with those changes to the submodule I'll merge them. Seems like a useful addition
