### ISSUE TITLE
MacOS Compile issue 4.24.3

### ISSUE THREAD

**Issue by ZhymonNorman** [getnamo/socketio-client-ue4#197]
![image](https://user-images.githubusercontent.com/7263210/78822451-13645d80-79a9-11ea-8273-d1db30e1b128.png)

The plugin is in the project directory, the latest release. 
UE4: 4.24.3

**Comment by getnamo** [comment]
I don't have a mac, so this will depend on other users replicating the issue and helping. Have you tried to pull the repository with --recurse-submodules?

**Comment by kjsujesh** [comment]
I was able to build this on a Mac. Like @getnamo suggested, do the recurse-submodules.

**Comment by getnamo** [comment]
Also check latest 4.25 plugin build, it should have additional MacOS pragma barrier which should bypass this issue
