### ISSUE TITLE
Not working on windows

### ISSUE THREAD

**Issue by nitinjain442** [getnamo/socketio-client-ue4#203]
I have downloaded unreal engine 4.24 and 4.25. When i open the sioclient uproject file in unreal, it says the plugin modules are missing and you need to rebuild them. I click yes and then it says "it could not be compiled. Try building from source manually." I don't know what i should do. I have tried downloading the new version of socketio-client also and have tried moving the plugin files around and changing the uplugin file also.

**Comment by getnamo** [comment]
marketplace release or https://github.com/getnamo/socketio-client-ue4/releases? if the latter, did you click on the .7z link?

**Comment by nitinjain442** [comment]
This link doesn't contain the sioclient.uproject file though

**Comment by nitinjain442** [comment]
And it still doesn't work

**Comment by nitinjain442** [comment]
Solved: i converted the sioclient.uproject file into the 4.25 version and it worked all of a sudden
