### ISSUE TITLE
Keeping track of character's x, y and z coordinates as it moves around and then use the socketio client to send those to the nodejs server

### ISSUE THREAD

**Issue by nitinjain442** [getnamo/socketio-client-ue4#204]
Is there a way in unreal engine to see the coordinates update as the character moves around and also send each of these coordinate pairs to a nodejs server using the socketio-client provided here?

**Comment by getnamo** [comment]
You should be able to just get your desired actor position as a vector, then [auto-cast it to a SIOJsonObject and then SIOJsonValue](https://github.com/getnamo/socketio-client-ue4#structs) and [emit](https://github.com/getnamo/socketio-client-ue4#sending-data-or-emitting-events-to-server) that to your server. In your server it will arrive as e.g. {x:1, y:2, z:3} json object.

**Comment by nitinjain442** [comment]
oh that makes sense. But how do i get the actor position constantly for wherever the actor is located when i keep moving it around using the arrow keys? This is what i'm most confused about i think

**Comment by getnamo** [comment]
That's a fairly generic question, it would be pertinent to look into the basic official documentation in unreal: https://docs.unrealengine.com/en-US/BlueprintAPI/Utilities/Transformation/GetActorLocation/index.html or use youtube tutorials like https://www.youtube.com/watch?v=kXSDmfl_wtA (check out his very comprehensive video list: https://www.youtube.com/channel/UCOVfF7PfLbRdVEm0hONTrNQ)

Generally in your ```OnTick``` event, call ```GetActorLocation```

**Comment by nitinjain442** [comment]
GetActorLocation gets you the starting location but doesn't update as you move around. I'll look into it though. thx

**Comment by nitinjain442** [comment]
Any ideas on getting location that updates? can't find in the documentation or videos

**Comment by getnamo** [comment]
GetActorLocation does update each time you call it. It gets the position of the RootComponent of the Actor you call it on.

If the value isn't changing there are two reasons: either you're not calling it multiple times (you likely want this to be called OnTick event in your instance), or you are not moving the root component in the actor, if that is the case you need to get the location of the component that is moving.

Learn about how to move an actor: https://www.youtube.com/watch?v=68pmsZ2L3PE

With that I'm closing the issue as the questions are now out of scope for the plugin. Try https://discord.com/invite/unreal-slackers or https://forums.unrealengine.com/ for basic unreal questions.

**Comment by nitinjain442** [comment]
Okay, thanks for the help!!
