### ISSUE TITLE
Trying to emit vector to server but the chat window opens up when going to localhost:3000 and not seeing the vector json objects 

### ISSUE THREAD

**Issue by nitinjain442** [getnamo/socketio-client-ue4#205]
I am trying to emit the vector positions of the actor to the server by converting the vector into a sio json value and then emiting it but when i go to localhost, the chat window is there and I don't see the vectors. Would i have to create my own server somehow? Does the index.js file need to be changed?

**Comment by nitinjain442** [comment]
The connection is being established but not getting the desired output

**Comment by getnamo** [comment]
Can you share blueprint screenshots of what you're doing?

**Comment by nitinjain442** [comment]
![Capture](https://user-images.githubusercontent.com/44326061/85030401-08654080-b143-11ea-96b3-86a21e0d01fe.PNG)

**Comment by nitinjain442** [comment]
Changing the port number and adding print after emit both don't do anything either.

**Comment by nitinjain442** [comment]
Oh wait, I think the problem is that the getactorlocation node isn't being activated and the event tick has to be connected to the getactorlocation node as well?

**Comment by nitinjain442** [comment]
I just named a random event name. Is it supposed to do something? in the sample you provided, it didn't seem to have any major function

**Comment by nitinjain442** [comment]
<img width="499" alt="1" src="https://user-images.githubusercontent.com/44326061/85076942-cc53cf00-b186-11ea-97ac-60aac8fc11e4.PNG">

**Comment by getnamo** [comment]
So a couple of things:
1. That's the web client source, not the server source.
2. The node.js server needs to 1) be running, 2) have the event you're emitting bound. 3) emit it back out to the other clients you want to receive that event.

In the chat example provided, the server receives the 'chatEvent' with a string parameter and multicasts that out to all clients as 'chatMessage'. If you'd want your website client to receive your position, you'd need to multicast out that specific event to the clients and bind to that event on your client so they receive it.

The example chatEvent multicast on the node.js server: https://github.com/getnamo/socketio-client-ue4-example/blob/master/server/index.js#L33

**Comment by nitinjain442** [comment]
what is the nodejs server and how is it activated? is it not the "node index.js" command? Also, what is meant by having the event you emit bound?

**Comment by nitinjain442** [comment]
<img width="415" alt="2" src="https://user-images.githubusercontent.com/44326061/85147660-cc021500-b214-11ea-8594-a239c4473ff0.PNG">

This is the output I am getting now.

**Comment by nitinjain442** [comment]
<img width="164" alt="x" src="https://user-images.githubusercontent.com/44326061/85152829-15556300-b21b-11ea-99ea-263ed9376028.PNG">

I have the coordinates printing out now and it seems to be solved when i go straight from the vector to a json string value but get [object Object] as my output when going from the vector to the json object to the json value.

**Comment by nitinjain442** [comment]
<img width="164" alt="x" src="https://user-images.githubusercontent.com/44326061/85173316-966f2300-b238-11ea-8172-0963742706e5.PNG">

I had the wrong event name.
I have the coordinates printing out now and it seems to be solved when i go straight from the vector to a json string value but get [object Object] as my output when going from the vector to the json object to the json value. How can i make it print as a {x:1, y:2, z:3} json object.

**Comment by nitinjain442** [comment]
I have the coordinates printing out now when the person moves after binding everything. Is there a way I could make it so that when I type a coordinate into the chat box on the web client server, my person in unreal will move to that location using the plugin?

**Comment by getnamo** [comment]
Yep that would be communicating the other way around. You'd likely want to parse the string you type in chat messages, e.g. ```/move 1 2 3``` either on client or server. In this instance it would likely be simpler to do it on server side.

E.g.  You'd modify https://github.com/getnamo/socketio-client-ue4-example/blob/master/server/index.js#L33 to check ```msg``` for your move command, split remainder by ' ' (space) and fill a vector formatted object. Then emit a new event either to all clients (easier) or the specific ue4 client (you'd need to store the socket.id so you can reference it here). Assuming the easier path it would be something like:

```javascript
socket.on(chatEvent, msg =>{
	//it's a command
	if (msg.substring(0,1) == '/'){
		//move command
		if (msg.substring(1,5) == "move"){
			//separate each param into an array
			let locArray = msg.substring(5).split(' '); 
			//convert to vector object
			let location = {x:locArray[0], y:locArray[1], z:locArray[2]};
	 
			//multicast new event to all clients
			io.emit('move', location);
		}
	}
});
```

Then in your unreal client you'd bind to the ```move``` event and convert the result into a vector which you'd use to *SetActorLocation*. NB: I haven't tested this code, you may need to convert string numbers to raw numbers, but it might just work as is.

**Comment by nitinjain442** [comment]
where node in unreal would get me the result that I am trying to convert into a vector?

**Comment by nitinjain442** [comment]
<img width="808" alt="11" src="https://user-images.githubusercontent.com/44326061/85365157-5d5dd980-b4ea-11ea-9c29-549fa3112e08.PNG">
<img width="797" alt="12" src="https://user-images.githubusercontent.com/44326061/85365163-5fc03380-b4ea-11ea-8aa0-4a81dfd9c562.PNG">


Not getting any output on the unreal screen when i type move in web browser which I should. (was getting for a few minutes and then it suddenly stopped). I am just testing that part before trying to move the actual actor

**Comment by nitinjain442** [comment]
<img width="493" alt="13" src="https://user-images.githubusercontent.com/44326061/85365362-cf362300-b4ea-11ea-9487-9b6d5a1293ef.PNG">
<img width="419" alt="14" src="https://user-images.githubusercontent.com/44326061/85365383-e117c600-b4ea-11ea-8111-fe55d477a623.PNG">
