### ISSUE TITLE
Does it support to connect to domain which is not raw ip address?

### ISSUE THREAD

**Issue by seasonseong** [getnamo/socketio-client-ue4#206]
I want to connect to Amazon api gateway webserver. that's domain is "wss://api-id.execute-api.region.amazonaws.com/stage". It works on javascript wscat module, but doesn't works on your following sample (https://github.com/getnamo/socketio-client-ue4/blob/master/README.md#c-fsocketionative). Please check this.

**Comment by seasonseong** [comment]
Well, i did unittest with websocket++ because socketio-client-ue4 uses that libraries. It looks doesn't work on websocket++ too.

**Comment by seasonseong** [comment]
I succeed to connect that uri. The problem was SSL. I followed this sample https://github.com/zaphoyd/websocketpp/issues/706

**Comment by getnamo** [comment]
SSL support is an ongoing high priority issue: https://github.com/getnamo/socketio-client-ue4/issues/39

non-ssl connections should work as expected e.g. http://myserver.com:3000

**Comment by seasonseong** [comment]
Thanks for reply. I'm expect it.

**Comment by seasonseong** [comment]
i succeed to connect with your plugin by editting a little code. i'll offer if you need.
