### ISSUE TITLE
Trying to convert json string into a vector

### ISSUE THREAD

**Issue by nitinjain442** [getnamo/socketio-client-ue4#208]
I am getting json strings such as [45, 56, 67] which i am trying to convert into a vector that i can use but am not able to. When i try converting to object and then json object to struct, unreal crashes sometimes. How can i get the vector?

**Comment by getnamo** [comment]
the json string should be {"x":45, "y":56, "z":67} and then the struct auto-conversion to a vector struct will work

**Comment by nitinjain442** [comment]
which node is this? construct json object value?

**Comment by nitinjain442** [comment]
<img width="564" alt="99" src="https://user-images.githubusercontent.com/44326061/85665850-646b2000-b681-11ea-85b4-acbb81b7fae2.PNG">

When i do this, the actor goes to 0, 0, 0 every time. I have checked to make sure that the string is in the format that you said.

**Comment by getnamo** [comment]
See https://github.com/getnamo/socketio-client-ue4#decoding-responses for decoding, you want to convert value to object and then fill the struct from the object.

**Comment by nitinjain442** [comment]
<img width="523" alt="21" src="https://user-images.githubusercontent.com/44326061/85743326-8e483500-b6c9-11ea-9f87-513f227f3891.PNG">

I am still getting 0 for all the coordinate values
