### ISSUE TITLE
changing ip address and port from UI

### ISSUE THREAD

**Issue by nitinjain442** [getnamo/socketio-client-ue4#212]
Is there a way I could type in the address and port i want to connect to instead of just manually hardcoding one like the default? It seems like you can turn the should auto connect to false and then use the connect node but how can i make user type in the address and port and then use that to set it?

**Comment by getnamo** [comment]
That's correct. For user input, if you want it at runtime, try using a UMG textbox widget (https://youtu.be/tc9QpPzmrsM) btw that YouTube channel has a great selection of unreal tutorial videos which I recommend for basic unreal how to

**Comment by nitinjain442** [comment]
is there a way I could set a variable to what the user typed though? i can't seem to find anything about this
