### ISSUE TITLE
storing json/vectors in buffers in unreal

### ISSUE THREAD

**Issue by nitinjain442** [getnamo/socketio-client-ue4#213]
Is there a way i could store coordinates in some sort of buffer using this plugin or in unreal?

**Comment by getnamo** [comment]
Do you mean serialized as bytes or just held in memory?

Just making an array of vectors and adding a new vector to the array will hold it in memory. If you mean instead serialization for storage, you can make a new BP struct with an array of vectors as a property and then you can use the struct to json and encode JSON blueprint nodes to serialize it into a JSON string (which you can save as a file)
