### ISSUE TITLE
Changing address and port of socketio from .ini file

### ISSUE THREAD

**Issue by nitinjain442** [getnamo/socketio-client-ue4#214]
Is there a way where you can change the address and port you want to connect to in a .ini file before starting up the executable?

**Comment by getnamo** [comment]
General settings are not exposed to an .ini file, but you could define an address/port in e.g. a json file and load the file and read the values on begin play and connect those

**Comment by getnamo** [comment]
You can load json via e.g. https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SIOJson/Public/SIOJLibrary.h#L171 which is globally available in BP

**Comment by nitinjain442** [comment]
can this be done after getting the executable file also? I want to be able to change port and address within the executable

**Comment by getnamo** [comment]
The file read will work after packaging, just mind the relative path

**Comment by nitinjain442** [comment]
I'm confused as to where I would want to add this c++ code. Also, the load json file to struct node only returns a boolean but we need a string for the address and port.

**Comment by getnamo** [comment]
You define a struct (can be BP defined) that matches the JSON data you want to read (see examples in readme), then you pass that struct in the 'any struct' parameter in the load file command. The Boolean returned specifies if the operation completed successfully.

For passing in the result as a single string, you can concatenate two strings defining IP/address and port in the right format.

**Comment by nitinjain442** [comment]
Is there a way I can set the relative path from the json file also? since the path might probably be different after packaging it

**Comment by getnamo** [comment]
It shouldn't be if you're using e.g. game/project directory path utility as base which adapts to fit current program form (editor/packaged).

But not you can't specify a path in the file you'd need the path to read it from.

**Comment by nitinjain442** [comment]
Don't you have to specify a path in the load json file to struct node? so the path will automatically change after packaging it?

**Comment by nitinjain442** [comment]
C:\Projects\unreal-env\Address.json

So if this is the path i specify in the editor, it will change after packaging? Does it matter where i package the project??

**Comment by nitinjain442** [comment]
Also, my editor is crashing when I try using the load json to struct for some reason

**Comment by getnamo** [comment]
Using something like https://docs.unrealengine.com/en-US/BlueprintAPI/Utilities/Paths/GetProjectFilePath/index.html as your base path to what you append relative paths will automatically adjust based on program form

**Comment by getnamo** [comment]
For crash, post a screenshot of your struct and  blueprint calling the load into that struct. Keep in mind the struct you load into should either be a function local or bp member variable and the key naming in struct should match your json

**Comment by nitinjain442** [comment]
![image](https://user-images.githubusercontent.com/44326061/87325916-adcbc400-c4f7-11ea-86e0-55aeb677fb94.png)

**Comment by getnamo** [comment]
You're passing in a string not a struct, this is why it's crashing. See e.g. https://github.com/getnamo/socketio-client-ue4#json-object-to-struct-example section for example how to match your custom bp struct to match your json format

**Comment by nitinjain442** [comment]
<img width="522" alt="json" src="https://user-images.githubusercontent.com/44326061/87328050-8aeedf00-c4fa-11ea-9741-7b151da68b6e.PNG">
<img width="236" alt="json1" src="https://user-images.githubusercontent.com/44326061/87328062-8d513900-c4fa-11ea-9b05-0f7a998a6eab.PNG">
<img width="485" alt="json2" src="https://user-images.githubusercontent.com/44326061/87328067-8fb39300-c4fa-11ea-917c-9020bb85cc6b.PNG">

It's not crashing anymore but it seems like it is unable to read what's in the json file since it is not connecting to the server. I have the json file in the same place as the uproject file and not sure what is happening

**Comment by nitinjain442** [comment]
I've tried using encode json to single string also, but when i print it to check, it prints {"address": ""} and not the address or port that i set it to

**Comment by getnamo** [comment]
Looks like you're forgetti g to append the file name to your path. Need the full path including the extension .json to load correctly

**Comment by nitinjain442** [comment]
<img width="558" alt="j2" src="https://user-images.githubusercontent.com/44326061/87351718-753fe080-c51f-11ea-83b4-1f017cf90738.PNG">

It's reading the file now and printing out {"address": "http://localhost:3000"}, but the connection isn't happening to the server when connecting it to the connect node.

**Comment by getnamo** [comment]
Once you've loaded the json to the struct, you should access it's address string property and feed that into the connect node. What you're currently doing is re encoding it to a json string and passing that in which isn't a valid URL format.

**Comment by nitinjain442** [comment]
How would I access the string property?

**Comment by getnamo** [comment]
Use Break struct or split struct blueprint features to access property members of a struct

**Comment by nitinjain442** [comment]
After packaging, I am unable to see the json file anywhere

**Comment by nitinjain442** [comment]
<img width="541" alt="js" src="https://user-images.githubusercontent.com/44326061/87359443-6c560b80-c52d-11ea-8fcc-dfb322c8119f.PNG">

**Comment by nitinjain442** [comment]
I tried copying the json file into the packaged directory and that didn't work either

**Comment by getnamo** [comment]
Print the full path you're getting before loading JSON to log and see where it's pointing to.

Regarding auto copying the JSON file you need to add the folder it's contained in as additional non assets files to copy https://answers.unrealengine.com/questions/155431/how-do-i-package-random-files.html

**Comment by nitinjain442** [comment]
It seems like packaging prints out the exact same path as before packaging. How can this be fixed?

**Comment by getnamo** [comment]
Try other Paths available as blueprint utilities, e.g.  root dir, or project saved for (see https://docs.unrealengine.com/en-US/BlueprintAPI/Utilities/Paths/index.html for available paths)

**Comment by nitinjain442** [comment]
It works with the project dir node. Also, this is kind of a side question but do you know what could cause third player character movement to glitch when moving left or right in the packaged version? is it something with the plugin cause it didn't happen before?
