### ISSUE TITLE
trying to emit two strings to server

### ISSUE THREAD

**Issue by nitinjain442** [getnamo/socketio-client-ue4#216]
i am trying to emit two strings, the name of the level and a door number. How could i combine them into a struct or something and emit the message? can you create like a vector of strings or something and label it however you want instead of converting the strings to ints and then having to emit has a vector of x and y

**Comment by getnamo** [comment]
Make a BP struct with two string properties and use the struct to JSON object node to convert the struct and then you can emit it as is. You can change property type pretty liberally as long as your server decodes them the same way
