### ISSUE TITLE
Linux Untested

### ISSUE THREAD

**Issue by getnamo** [getnamo/socketio-client-ue4#22]
Linux build needs basic testing to confirm it works as intended.

**Comment by cpyarger** [comment]
Checking with current 4.17 branch of unreal and latest Socket.IO pull from the master branch, I will let you know how it goes

**Comment by cpyarger** [comment]
I was unable to compile as an Engine Plugin due to the plugin not following this standard for Engine Plugins.

I am currently compiling as a Game /Project Plugin

**Comment by cpyarger** [comment]
I have tried 4.15, 4.16, 4.17 and I am getting this same error in all of them. I have tried to recompile the socketio files using boost, and nothing changes. I am at a loss for the night. Any ideas?

```
[10/11] Link libUE4Editor-SocketIOClient.so
/usr/bin/ld: ~Documents/Unreal Projects/MyProject/Plugins/socketio-client-ue4-15/ThirdParty/SocketIO/Lib/Linux/libsioclient.a(sio_socket.cpp.o): relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC
~/Documents/Unreal Projects/MyProject/Plugins/socketio-client-ue4-15/ThirdParty/SocketIO/Lib/Linux/libsioclient.a: error adding symbols: Bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ERROR: UBT ERROR: Failed to produce item: ~/Documents/Unreal Projects/MyProject/Plugins/socketio-client-ue4-15/Binaries/Linux/libUE4Editor-SocketIOClient.so


```

**Comment by getnamo** [comment]
re-pull master (v0.12.7), it should now compile using your own linux toolchain and thus avoid these linking errors. Let me know if new issues arise.

**Comment by chuan9** [comment]
@getnamo Hi, Failed to cross-compile project, the root cause is: https://github.com/getnamo/tensorflow-ue4/issues/11. No prebuild binary for linux, Do you have any suggestions? thx

**Comment by getnamo** [comment]
> @getnamo Hi, Failed to cross-compile project, the root cause is: [getnamo/tensorflow-ue4#11](https://github.com/getnamo/tensorflow-ue4/issues/11). No prebuild binary for linux, Do you have any suggestions? thx

What version of socket.io plugin are you using?

Tensorflow-ue4 has other issues for compiling on linux that are not related to this plugin.

**Comment by chuan9** [comment]
@getnamo  Unreal 4.21.2, and it gives me tips no prebuild binary.
 and I use source code instead of market plugin, cross-compile can be successful! Thanks, just FYI

**Comment by getnamo** [comment]
New binary release: https://github.com/getnamo/socketio-client-ue4/releases/tag/1.0.0 now includes linux support. Ensure you have followed basic cross compile setup for linux https://docs.unrealengine.com/en-us/Platforms/Linux/GettingStarted

**Comment by getnamo** [comment]
Working in release, closing issue. Open new issue if something crops up with linux.
