### ISSUE TITLE
Files missing include for log category

### ISSUE THREAD

**Issue by gmpreussner** [getnamo/socketio-client-ue4#222]
The following files are missing an include for `SIOMessageConvert.h`, which is where the `SocketIOLog` category is declared. Without the include, non-unity builds will fail:

* `SocketIOClient/Private/SocketIOClient.cpp`
* `SocketIOClient/Private/SocketIOClientComponent.cpp`

Also, you may want to consider renaming the log category to `SocketIO`, because the `DECLARE_LOG_CATEGORY` macro already prepends a `Log`, so you effectively end up with `LogSocketIOLog` as the category name.

**Comment by getnamo** [comment]
merged here: https://github.com/getnamo/socketio-client-ue4/commit/0ad59efc2b56ef4915dcb44614ab3fccf89d55fb
