### ISSUE TITLE
sio_socket.cpp missing declaration for LOG macro

### ISSUE THREAD

**Issue by gmpreussner** [getnamo/socketio-client-ue4#223]
The `SocketIOLib/Private/sio_socket.cpp` file missing a declaration for the `LOG` macro. This breaks non-unity server builds.

Temporary workaround: `#define LOG(x)`

**Comment by getnamo** [comment]
Do you think https://github.com/getnamo/socketio-client-ue4/pull/224 is sufficient? 

I haven't tested this pull yet, just wanted to see if at a glance it appears to address #223 and #222; will need to come back to it when I have more time to do regression test on all supported platforms

**Comment by gmpreussner** [comment]
Yeah, that should be fine. It's what I ended up doing - sorry, I couldn't provide a pull request, because I was working remotely to unblock one of my clients. Thanks!

**Comment by getnamo** [comment]
Merged in https://github.com/getnamo/socketio-client-ue4/commit/0ad59efc2b56ef4915dcb44614ab3fccf89d55fb
