### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by viktorkatsava** [getnamo/socketio-client-ue4#226]
UATHelper: Packaging (Windows (64-bit)):     [2/14] SharedPCH.Core.cpp
UATHelper: Packaging (Windows (64-bit)):     [3/14] Car_Customize.cpp
UATHelper: Packaging (Windows (64-bit)):     [4/14] SharedPCH.Engine.cpp
UATHelper: Packaging (Windows (64-bit)):     [5/14] SharedPCH.Engine.RTTI.Exceptions.cpp
UATHelper: Packaging (Windows (64-bit)):     [6/14] Module.CoreUtility.gen.cpp
UATHelper: Packaging (Windows (64-bit)):     [7/14] Module.SIOJson.gen.cpp
UATHelper: Packaging (Windows (64-bit)):     [8/14] Module.CoreUtility.cpp
UATHelper: Packaging (Windows (64-bit)):     [9/14] Module.SocketIOClient.gen.cpp
UATHelper: Packaging (Windows (64-bit)):     [10/14] Module.SIOJson.cpp
UATHelper: Packaging (Windows (64-bit)):     [11/14] Module.SocketIOClient.cpp
UATHelper: Packaging (Windows (64-bit)):     [12/14] Module.SocketIOLib.cpp
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C4430: ��������� ᯥ�䨪��� ⨯� - �।���������� int. �ਬ�砭��. C++ �� �����ন���� int �� 㬮�砭��
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2059: ᨭ⠪��᪠� �訡��: >
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2059: ᨭ⠪��᪠� �訡��: )
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xf0"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x7"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xf9"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xb0"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x98"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x8c"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x80"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x40"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xae"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xfc"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xff"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x29"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C3872: 0x40: ��� ᨬ��� ���������� �ᯮ�짮���� � �����䨪���
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x7f"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xf2"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x41"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x10"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xf5"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xe8"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xeb"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x42"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x81"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xee"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x15"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xf"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xe1"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x82"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xe4"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x9"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xe7"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xa0"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x60"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x83"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xda"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x90"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xdd"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x84"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xd0"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xd3"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x85"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xd6"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xc9"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x86"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xcc"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xf3"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x6"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xc"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x1"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xcf"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x43"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x87"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xc2"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0xc5"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x88"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x44"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x89"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x8a"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x45"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x8b"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x8d"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.hpp(1): error C2018: ��������� ���� "0x8e"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.ipp(30): error C2143: ᨭ⠪��᪠� �訡��: ������⢨� ";" ��। "{"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v4.ipp(30): error C2447: {: ��������� ��������� �㭪樨 (��������, �ᯮ������ �ଠ��� ᯨ᮪ ��ண� ⨯�)
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0xa8"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0xae"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0x7"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0xf8"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0x98"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0x8c"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0xb0"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C4430: ��������� ᯥ�䨪��� ⨯� - �।���������� int. �ਬ�砭��. C++ �� �����ন���� int �� 㬮�砭��
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2146: ᨭ⠪��᪠� �訡��: ������⢨� ";" ��। �����䨪��஬ "
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2059: ᨭ⠪��᪠� �訡��: )
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0x13"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C3872: 0x13: ��� ᨬ��� ���������� �ᯮ�짮���� � �����䨪���
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0xe"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0x1"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0xf0"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0xe0"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0xfb"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0x8a"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0x40"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0xa9"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0xfe"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2014: ������� �९����� �� ������ ��稭����� � �஡���
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0x4e"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0x29"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0x9"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0x4f"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0xaa"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0xf4"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0x51"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0xa0"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0x60"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0xab"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0xea"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0x50"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0x90"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0xac"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): error C2018: ��������� ���� "0x80"
UATHelper: Packaging (Windows (64-bit)):     d:\unreal projects\carconfiger_steaming\plugins\socketio-client-ue4\source\thirdparty\asio\asio\include\asio/ip/impl/address_v6.hpp(1): fatal error C1003: �᫮ �訡�� �ॢ�蠥� 100; ��⠭���� �������樨

UATHelper: Packaging (Windows (64-bit)): Took 135,0407239s to run UnrealBuildTool.exe, ExitCode=5
UATHelper: Packaging (Windows (64-bit)): UnrealBuildTool failed. See log for more details. (C:\Users\V\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+Program+Files+UE_4.24\UBT-Car_Customize-Win64-Development_2.txt)
UATHelper: Packaging (Windows (64-bit)): AutomationTool exiting with ExitCode=5 (5)
UATHelper: Packaging (Windows (64-bit)): BUILD FAILED
PackagingResults: Error: Unknown Error

**Comment by getnamo** [comment]
Platform? How is this code being included?

**Comment by getnamo** [comment]
closed due to lack of followup
