### ISSUE TITLE
use ws://localhost:3000 It doesn't work

### ISSUE THREAD

**Issue by ouyang-yuxuan** [getnamo/socketio-client-ue4#231]
html：（The normal work）
```
<script type="text/javascript">
         function WebSocketTest()
         {
            if ("WebSocket" in window)
            {
               var ws = new WebSocket("ws://localhost:3000");
               ws.onopen = function()
               {
               };
               ws.onmessage = function (evt) 
               { 
                  var received_msg = evt.data;
                  alert(received_msg)
               };
               ws.onclose = function()
               { 
               };
            }
            else
            {
            }
         }
      </script>
```
![image](https://user-images.githubusercontent.com/36830421/92553045-9d845b00-f294-11ea-8a20-74122a31dd2a.png)
socket io  It doesn't work
Springboot WebSocket used in the websocketserver
cannot connect to the server using http://localhost:3000

**Comment by getnamo** [comment]
you can't use a plain websocket server, you need to use socket.io protocol or it won't work. See https://socket.io/ for server examples

**Comment by ouyang-yuxuan** [comment]
> you can't use a plain websocket server, you need to use socket.io protocol or it won't work. See https://socket.io/ for server examples

Thank you very much. I know how to use it.
Server Java Netty-socketio, Ue4 Socketio Ondisconnect does not work, the server sends messages to the client normally and receives them.But the clients disonnect and Ondisconnect don't work.

**Comment by getnamo** [comment]
If you're force quitting the server, try listening to onconnectionproblems instead, you may never get a 'disconnected' message if the server quit non-gracefully

**Comment by ouyang-yuxuan** [comment]
> If you're force quitting the server, try listening to onconnectionproblems instead, you may never get a 'disconnected' message if the server quit non-gracefully

I see. Thank you very much.The client's disconnect didn't work, but now it does, but the server doesn't listen for disconnect.I don't know what went wrong, kind of weird

**Comment by ouyang-yuxuan** [comment]
> > If you're force quitting the server, try listening to onconnectionproblems instead, you may never get a 'disconnected' message if the server quit non-gracefully
> 
> I see. Thank you very much.The client's disconnect didn't work, but now it does, but the server doesn't listen for disconnect.I don't know what went wrong, kind of weird

Only if the client forces an exit can the server listen
