### ISSUE TITLE
Just ask how the global can be called SocketIOClient

### ISSUE THREAD

**Issue by ouyang-yuxuan** [getnamo/socketio-client-ue4#232]
I don't want to be restricted to components in actors, just ask how the global can be called.For example, I want to use Construct Json Request, but I just reference it directly in gamemodel and it crashes.Even if I create a new SocketIOClientComponent in the Gamemodel

**Comment by getnamo** [comment]
You want to statically allocate a SocketIOClientComponent, see https://github.com/getnamo/socketio-client-ue4#statically-constructed-socketioclient-component section. You should be able to allocate that in all blueprint types and you can treat it as a regular UObject base. If that's not enough, you can always customize your own object type via [FSocketIONative](https://github.com/getnamo/socketio-client-ue4#c-fsocketionative) in c++.
