### ISSUE TITLE
Receive Event

### ISSUE THREAD

**Issue by hbt22video** [getnamo/socketio-client-ue4#233]
In cpp side, i am trying to receive message and only can bind static function to OnNativeEvent. I want to bind to nonstatic(dynamic) func.
Is it the only way binding static func or i am doing something wrong.
i am using 4.25 if it make difference.

**Comment by hbt22video** [comment]
if my question is not clear, please tell me because i am waiting your answer 👍

**Comment by getnamo** [comment]
You'll likely want to wrap your function in a lambda and call your dynamic event from there. See https://github.com/getnamo/socketio-client-ue4#receiving-events for an example

**Comment by hbt22video** [comment]
![image](https://user-images.githubusercontent.com/28192057/95199003-cdb41080-07e4-11eb-8342-48b3b93f6425.png)
i can call only static variable and function in this lambda section

**Comment by hbt22video** [comment]
do i need to write new "OnNativeEvent" with own parameter ?

**Comment by hbt22video** [comment]
is there any example of accessing other variable or function in lambda expression?

**Comment by getnamo** [comment]
Put ```this``` inside the square brackets in the beginning of the lambda definition, it will allow you to call functions from the calling context.

E.g.

 ```
[this]()
{
    //now you can call member functions
}
```

**Comment by hbt22video** [comment]
thank you for great help ^^
