### ISSUE TITLE
Parse JSON string

### ISSUE THREAD

**Issue by t0msk** [getnamo/socketio-client-ue4#234]
Hello,

this is my code in Blueprints, and I would like to ask you how can I parse JSON string in UE4? My server running on Node.js return this JSON:

`{"success":1,"player_name":"tomsk","player_session":"123","silver":"10","gold":"1"}`

Blueprint:

![Screenshot_20200920_210220](https://user-images.githubusercontent.com/7276200/93719796-2cdb1980-fb85-11ea-8356-ba9c639ea8e5.png)

So how can I get values from this JSON? Or for example how can I get single value like **success**?

**Comment by getnamo** [comment]
You need to likely decode your SIOJsonObject message into a struct, see https://github.com/getnamo/socketio-client-ue4#decoding-responses for example.

Regarding your struct, the case can be ignored but underscore ( _ ) is not the same as space ( ) so you may need to modify your struct to match exact names of struct.

**Comment by t0msk** [comment]
I got it, thanks :)

![Screenshot_20200921_123533](https://user-images.githubusercontent.com/7276200/93757464-1aa1bf80-fc07-11ea-807e-fe5af56053b3.png)
