### ISSUE TITLE
Plugin SocketIOClient failed to load because module SIOJson couldnt be found. UE4.25 plugin version  1.40. Build for Windows x64

### ISSUE THREAD

**Issue by viktorkatsava** [getnamo/socketio-client-ue4#235]
In log:
LogUObjectGlobals: Warning: Failed to find object 'Class None.SIOJJsonObject'
LogUObjectGlobals: Warning: Failed to find object 'Class None.SIOJJsonObject'

**Comment by getnamo** [comment]
The log message is not related (some left over warning I haven't debugged, it's harmless though).

Regarding your title: Ensure you are following the c++ guide correctly and including the modules in your build.cs files: https://github.com/getnamo/socketio-client-ue4#setup.

**Comment by AatmanRangrej** [comment]
Plugin SocketIOClient failed to load because module SIOJson couldnt be found.  UE 5.0 plugin version 2.0.1. Build for Android Target = 21+
