### ISSUE TITLE
How to display server messages without knowing event names

### ISSUE THREAD

**Issue by jessekirbs** [getnamo/socketio-client-ue4#236]
I'd like to try to use Socket.io to make a MUD client within Unreal. At its most basic, I'm trying to connect to the address (batmud.bat.org:23). I'm having a hard time understanding how to display the first text you see when connecting. Do I need to know the event name on the server to be able to display anything? For example, when you connect to batmud.bat.org:23it automatically shows a welcome message - I'd like to get that to show when you connect via Unreal but as far as I can tell I need to know the name of the event (e.g. chatMessage). Could you please help me understand if what I want is possible? Thank you!

**Comment by getnamo** [comment]
Is the service using socket.io protocol? If not you need to use a lower level protocol like tcp, https://github.com/getnamo/tcp-ue4 (or udp) to connect to your service
