### ISSUE TITLE
Construct JosnRequest SetHeader it does't work

### ISSUE THREAD

**Issue by ouyang-yuxuan** [getnamo/socketio-client-ue4#238]
![image](https://user-images.githubusercontent.com/36830421/94398495-36bdd780-0198-11eb-84a7-5e59ab5b0867.png)
Construct JosnRequest SetHeader it does't work.Server can't get Header.

**Comment by getnamo** [comment]
Can you give an example of whats expected? Vs what the server receives? This isn't a core functionality of the plugin, but it could be looked at in the next update cycle

**Comment by ouyang-yuxuan** [comment]
> Can you give an example of whats expected? Vs what the server receives? This isn't a core functionality of the plugin, but it could be looked at in the next update cycle

I've found the solution. I need to change the JSON request into a variable before the set header, and then use the variable after the applyUrl

![image](https://user-images.githubusercontent.com/36830421/95284695-62744800-0891-11eb-8f77-f43f2be180f0.png)

**Comment by getnamo** [comment]
That makes sense, construct json request shouldn't be pure as order of ops matters
