### ISSUE TITLE
Socket.io v3 released

### ISSUE THREAD

**Issue by Wadimich** [getnamo/socketio-client-ue4#245]
Hello! Will you make support for new socket.io v3 version? It seems, that there is no backwards compatibility and v2 client can't connect to v3 server and vice versa.

**Comment by getnamo** [comment]
This plugin depends on https://github.com/socketio/socket.io-client-cpp/ (we use a variant of https://github.com/getnamo/socket.io-client-cpp/tree/non-boost), when there is a version with 3.0 support, it will get merged and added. That said the base changes in socket.io protocol feel fairly small and we may need to implement the changes ourselves if that repo doesn't update

**Comment by xeru98** [comment]
The main branch at https://github.com/socketio/socket.io-client-cpp/ has been updated to have 3.0 support. Any chance you will be revisiting the upgrade or are you waiting for whenever helios fixes their branch?

**Comment by getnamo** [comment]
That's great news, I'll have a look at merging their fixes for v3, it should be sufficiently compatible.

**Comment by EnricoPietrocola** [comment]
+1 on this v3 possibility, I'd love to start playing with unreal and socketio v3

**Comment by jonahbedouch** [comment]
For those waiting on this feature, it is helpful to note that as of Socket.io v3.1.0, Socket.io v3 servers should technically have support for connecting to v2 clients (with the `allowEIO3` setting enabled). While I've not tested this yet myself, it should allow you to upgrade your server to v3 immediately, then upgrade the client whenever it becomes available. More info [here](https://socket.io/docs/v3/migrating-from-2-x-to-3-0/#How-to-upgrade-an-existing-production-deployment).

**Comment by richardeakin** [comment]
Has anyone gotten the socket-client-ue4 working when the `allowEIO3` flag is added to the server? I tried the following and it still doesn't work, I don't even get an `On Connected` node firing.

```
var io = require('socket.io')(http, {
        allowEIO3: true // enables using v2 socket.io-clients
    }
);
```

**Comment by MichaelJCole** [comment]
I can confirm that a server using  `"socket.io": "^4.0.0"` using this UE4 client doesn't emit an on 'connection' event on the server:

```
const SOCKETIO_CONFIG = {
  allowEIO3: true,
  cors: {
    origin: `http://localhost:${PORT}`,
  },
}
export const app = express()
app.use(express.json())
export const httpServer = http.createServer(app)
export const io = new Server(httpServer, SOCKETIO_CONFIG)
```
I have to rewrite the server to downgrade to version 2.0.

**The readme and the store page indicate you're selling this plugin for maintenance.  Is there a plan?**   I bought this on the marketplace and not maintaining those pages has wasted my time debugging and rewriting.

If you're not maintaining the plugin, please consider not selling it anymore.  Art is never finished, it's abandoned :-)

Thanks!

**Comment by getnamo** [comment]
Plugin base library update to v3/4 is on the docket, just no clear eta when that will happen (but likely ~next engine release version). Depends on availability of open source hours.

**Comment by dobby5** [comment]
Hello,

I have updated the c++ client integration in a folk. After my first test it is now possible to connect to socketio server with version 3.0 and 4.0 (and 2.0).

Maybe some people want to try the changes.
If everything works as desired I will post a PR.

https://github.com/dobby5/socketio-client-ue4/tree/socketio_3_0_4_0

**Comment by getnamo** [comment]
Great stuff @dobby5, appreciate that patch. I'll pull this over the weekend and test against some of the plugin edge cases.

**Comment by getnamo** [comment]
Pulled and merged back some changes in our variant of the lib. With those changes it worked as expected, awesome stuff.

Pull request https://github.com/getnamo/socketio-client-ue4/pull/264
Merge https://github.com/getnamo/socketio-client-ue4/commit/2e10de05fcc80dde4eaa8a6e6c881c2160e1eee4

Pending new github release

**Comment by getnamo** [comment]
Release: https://github.com/getnamo/socketio-client-ue4/releases/tag/1.6.0

**Comment by getnamo** [comment]
NB: Should support v3/v4 protocol, may break support for v2 servers (use older plugin versions for those)

**Comment by dobby5** [comment]
Hello @MichaelJCole ,

thank you for the kind words and that you are willing to support me financially.
I also bought the plugin on the marketplace back then and find it unfortunate that the plugin has not been developed much, until now. I have been waiting for SSL support for months.

But please let's not forget that you can't live on irregular income from plugin purchases. @getnamo will certainly be happy about the support in the form of money, but it also means that he can continue to maintain the plugin only in his spare time.
We should be a little tolerant with @getnamo , we live in hard times, however, this should not be an excuse for everything either.

I hope each of us can take a few things from it for ourselves.

I wish you all a nice pleasant day and maybe we will hear from each other again :)

Greeting
Dobby

**Comment by namxam** [comment]
@dobby5 Thank you for your help and the true and kind words. The plugin is very cheap and I guess it wont cover the costs of developing it.

@getnamo Thanks for the quick help. Unfortunately, the guy responsible for UE integration is off next week. So we have to wait, but we will give it a try the week after and let you guys know if any issues come up.

**Comment by MichaelJCole** [comment]
> Hello @MichaelJCole ,
> 
> thank you for the kind words and that you are willing to support me financially.
> I also bought the plugin on the marketplace back then and find it unfortunate that the plugin has not been developed much, until now. I have been waiting for SSL support for months.
> 
> But please let's not forget that you can't live on irregular income from plugin purchases. @getnamo will certainly be happy about the support in the form of money, but it also means that he can continue to maintain the plugin only in his spare time.
> We should be a little tolerant with @getnamo , we live in hard times, however, this should not be an excuse for everything either.
> 
> I hope each of us can take a few things from it for ourselves.
> 
> I wish you all a nice pleasant day and maybe we will hear from each other again :)
> 
> Greeting
> Dobby

You're right.  I'm just irritated with the lack of documentation, and I let it go.  Thanks for the great plugin.

**Comment by namxam** [comment]
@getnamo Any chance of a new UE 4.25 release?

**Comment by getnamo** [comment]
@namxam I normally don't backport releases, but I made one for you here: https://github.com/getnamo/socketio-client-ue4/releases/tag/1.6.0
