### ISSUE TITLE
client auto connect is always true

### ISSUE THREAD

**Issue by Darkloud91** [getnamo/socketio-client-ue4#249]
my client auto connect is always true. i dont know why always try to reconnect when server is down.

![image](https://user-images.githubusercontent.com/14833406/102022788-6b99fd80-3d89-11eb-8293-42f92a0555b1.png)

**Comment by getnamo** [comment]
Context for this static construct? See https://github.com/getnamo/socketio-client-ue4#note-on-auto-connect, some context may affect this toggle

**Comment by Darkloud91** [comment]
this is in game instance, i add the set autoconnect to false trying to disable it. Maybe im doing something wrong?

**Comment by getnamo** [comment]
In game instances auto-connect is disabled. 

Relevant section in readme: 
_Game Instances do not have actor owners and therefore cannot register and initialize the component. The only drawback is that you must manually connect. bShouldAutoConnect is disabled in this context._

You can safely ignore auto-connect toggle. NB auto-connect setting in this context means it connects to your server on begin play.

If you're looking for reconnection settings, adjust MaxReconnectionAttempts, ReconnectionDelayInMs, and ReconnectionTimeout settings. See https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SocketIOClient/Public/SocketIOClientComponent.h#L79 setting.

**Comment by Darkloud91** [comment]
but my game is always reconnecting  and i dont want that :/

**Comment by getnamo** [comment]
Right change MaxReconnectionAttempts on your component to 0
