### ISSUE TITLE
Get Session ID (Socket ID ?) seems always empty

### ISSUE THREAD

**Issue by st3ph** [getnamo/socketio-client-ue4#25]
I tried to print the Socket ID (named Session Id in the component via blueprints) as differents times in the game flow (construct => begin play => after emit...) and it seems to always be empty

Beside that, all is working great.

Is this a bug ? How can I get the Socket/Session ID ?

Thank you,

**Comment by getnamo** [comment]
I believe you are correct, I haven't seen it fill correctly either. Wasn't a priority then so I just left it in. Will tag this as a bug and have a look.

**Comment by getnamo** [comment]
fixed here: https://github.com/getnamo/socketio-client-ue4/commit/9699bf00a206bad303e684c3aaea5dbfc9dc836d in https://github.com/getnamo/socketio-client-ue4/pull/28
