### ISSUE TITLE
Packaged for Windows 10 (64-bit) executable fails because module 'SIOJson' could not be found

### ISSUE THREAD

**Issue by evgeniy-khist** [getnamo/socketio-client-ue4#250]
- Windows 10 (64-bit)
- Unreal Engine 4.26
- socketio-client-ue4 1.5.1

When trying to package for Win64 the sample https://github.com/getnamo/socketio-client-ue4-example and execute the binary `WindowsNoEditor\sioclient.exe` I have an error:

> Plugin 'SocketIOClient' failed to load because module 'SIOJson' could not be found.

<img width="312" alt="SIOJson Error" src="https://user-images.githubusercontent.com/1311126/103179334-927d2700-4893-11eb-97bc-79fb1f907254.png">

I package the project the following way:

<img width="266" alt="UE4-package" src="https://user-images.githubusercontent.com/1311126/103179335-9315bd80-4893-11eb-8955-965d61d51d34.png">

The issue is similar to https://github.com/getnamo/socketio-client-ue4/issues/54 but the described solution doesn't work in my case. I copied binaries instead of sources to the `Plugins` directory.

**Comment by getnamo** [comment]
You may need to add an empty c++ class to your project to force the engine to recompile the plugin for packaged mode.

**Comment by getnamo** [comment]
See https://github.com/getnamo/socketio-client-ue4#github

**Comment by evgeniy-khist** [comment]
@getnamo, thanks it works.
The only thing I had to do is adding an empty C++ class:
![Create empty C++ class](https://camo.githubusercontent.com/d9468c3238ea94004e839368b72b5ab33b1a7f328e377d4bbd779685e70f387f/68747470733a2f2f692e696d6775722e636f6d2f557277783254462e706e67)
