### ISSUE TITLE
Cannot open include file: 'websocketpp/client.hpp" : No such file or directory. 

### ISSUE THREAD

**Issue by Gerfeso** [getnamo/socketio-client-ue4#252]
Trying to compile but missing a file. 
Is this mean to be purchased or an open source project?

**Comment by getnamo** [comment]
open source, if you're using git, make sure to ```--recurse-submodules``` to pull the dependent third party libraries (also open source). See https://github.com/getnamo/socketio-client-ue4#via-git-clone for details

**Comment by Gerfeso** [comment]
that was it, thanks.
