### ISSUE TITLE
Support for python-socketio

### ISSUE THREAD

**Issue by jamiewilbraham** [getnamo/socketio-client-ue4#258]
Hi there,

Is there a version of python-socketio that will work with the latest socketio-client-ue4 version?

I seem to be getting the following error: 

![image](https://user-images.githubusercontent.com/13650672/115809589-7ef85c00-a440-11eb-9ace-4557fe1a6841.png)

Any help would be much appreciated!

TIA

**Comment by getnamo** [comment]
likely one that uses socket.io protocol v1 or v2. For newer versions it will depend on implementing https://github.com/getnamo/socketio-client-ue4/issues/245 which I need to do in the near term.

**Comment by getnamo** [comment]
Looking at https://python-socketio.readthedocs.io/en/latest/intro.html compatibility chart it would be 4.x

**Comment by jamiewilbraham** [comment]
Thanks for the help - will try it out
