### ISSUE TITLE
Referenced directory does not exist.

### ISSUE THREAD

**Issue by yexiuph** [getnamo/socketio-client-ue4#269]
![image](https://user-images.githubusercontent.com/42666658/120326423-48551180-c31b-11eb-916c-40af33fbbe5c.png)

Is this normal I'm not getting those in the past release.
Using UE5 EA

Quick fix if you're using UE5 EA - Copy the old includes from old releases then paste it into your UE5 plugin.

**Comment by getnamo** [comment]
You need to clone using submodules, see https://github.com/getnamo/socketio-client-ue4#via-git-clone note
