### ISSUE TITLE
gibberish：when node.js emit message in chinese,ue4 on the message is wrong

### ISSUE THREAD

**Issue by xiaoheitwo** [getnamo/socketio-client-ue4#27]
hellow,thanks for your plugin!
when I emit message from ue4 to node.js in chinese,receive message is right. but emit message from node.js to ue4 in chinese,receive message is wrong ,can you help me solve it?
thanks.

**Comment by getnamo** [comment]
Looks like utf8 encoding on receive isn't working, what method are you using to show the mesage?

**Comment by xiaoheitwo** [comment]
![image](https://cloud.githubusercontent.com/assets/20655908/21646650/ed7eb416-d2d1-11e6-9cbc-889289394024.png)

**Comment by xiaoheitwo** [comment]
Can you give me some tips, i can modify plugin by myself,this is really important for me,thanks...

**Comment by xiaoheitwo** [comment]
help help help...

**Comment by getnamo** [comment]
Still away for a few days but here are some points to look into (c++) https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SocketIOClient/Private/SocketIOClientComponent.cpp#L291 is the event that handles the blueprint 'On' event which uses this function https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SocketIOClient/Private/SocketIOClientComponent.cpp#L329 which calls https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SocketIOClient/Private/SIOMessageConvert.cpp#L10 which calls https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SocketIOClient/Private/SIOMessageConvert.cpp#L149 that is likely the culprit. Notice the .c_str(), we may need another conversion e.g. see https://forums.unrealengine.com/showthread.php?108002-Construct-a-FString-from-a-std-string-in-UTF-8-encoding

If you manage to fix it, make a pull request :)

**Comment by getnamo** [comment]
Fixed in https://github.com/getnamo/socketio-client-ue4/pull/28 test it and let me know if all your use cases pass.

**Comment by getnamo** [comment]
commit with fix: https://github.com/getnamo/socketio-client-ue4/pull/28/commits/294a3e764e8272da23104fccd29e76eaa1245893

**Comment by xiaoheitwo** [comment]
Wow,it works and what I use now is all ok. 
Really thanks.
