### ISSUE TITLE
android  package BUILD FAILED

### ISSUE THREAD

**Issue by mspcbs** [getnamo/socketio-client-ue4#274]
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   C:/Users/mspcb/Downloads/SIOClientExample-p1.6.0u4.26/socketio-client-ue4-example/sioclient/Plugins/socketio-client-ue4/Source/SocketIOLib/Private/internal/sio_client_impl.h(207,5): error: 'SIO_TLS' is not defined, evaluates to 0 [-Werror,-Wundef]
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   #if SIO_TLS
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):       ^
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   In file included from C:/Users/mspcb/Downloads/SIOClientExample-p1.6.0u4.26/socketio-client-ue4-example/sioclient/Plugins/socketio-client-ue4/Intermediate/Build/Android/UE4/Development/SocketIOLib/Module.SocketIOLib.cpp:2:
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   C:/Users/mspcb/Downloads/SIOClientExample-p1.6.0u4.26/socketio-client-ue4-example/sioclient/Plugins/socketio-client-ue4/Source/SocketIOLib/Private/internal/sio_client_impl.cpp(77,5): error: 'SIO_TLS' is not defined, evaluates to 0 [-Werror,-Wundef]
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   #if SIO_TLS
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):       ^
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   C:/Users/mspcb/Downloads/SIOClientExample-p1.6.0u4.26/socketio-client-ue4-example/sioclient/Plugins/socketio-client-ue4/Source/SocketIOLib/Private/internal/sio_client_impl.cpp(252,5): error: 'SIO_TLS' is not defined, evaluates to 0 [-Werror,-Wundef]
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   #if SIO_TLS
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):       ^
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   C:/Users/mspcb/Downloads/SIOClientExample-p1.6.0u4.26/socketio-client-ue4-example/sioclient/Plugins/socketio-client-ue4/Source/SocketIOLib/Private/internal/sio_client_impl.cpp(629,5): error: 'SIO_TLS' is not defined, evaluates to 0 [-Werror,-Wundef]
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   #if SIO_TLS
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):       ^
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   In file included from C:/Users/mspcb/Downloads/SIOClientExample-p1.6.0u4.26/socketio-client-ue4-example/sioclient/Plugins/socketio-client-ue4/Intermediate/Build/Android/UE4/Development/SocketIOLib/Module.SocketIOLib.cpp:5:
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   C:/Users/mspcb/Downloads/SIOClientExample-p1.6.0u4.26/socketio-client-ue4-example/sioclient/Plugins/socketio-client-ue4/Source/SocketIOLib/Private/sio_socket.cpp(34,5): error: 'DEBUG' is not defined, evaluates to 0 [-Werror,-Wundef]
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   #if DEBUG || _DEBUG
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):       ^
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   C:/Users/mspcb/Downloads/SIOClientExample-p1.6.0u4.26/socketio-client-ue4-example/sioclient/Plugins/socketio-client-ue4/Source/SocketIOLib/Private/sio_socket.cpp(34,14): error: '_DEBUG' is not defined, evaluates to 0 [-Werror,-Wundef]
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   #if DEBUG || _DEBUG
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):                ^
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   6 errors generated.
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   Error executing I:\NVPACK\android-ndk-r22-windows-x86_64\android-ndk-r22\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe (tool returned code: 1)
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   ---------------------- Done ----------------------
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):       Rebuild All: 0 succeeded, 1 failed, 0 skipped
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   1 build system warning(s):
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):      - License is invalid
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)):   
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)): Took 209.4495762s to run xgConsole.exe, ExitCode=1
PackagingResults: Error: 'SIO_TLS' is not defined, evaluates to 0 [-Werror,-Wundef]
PackagingResults: Error: 'SIO_TLS' is not defined, evaluates to 0 [-Werror,-Wundef]
PackagingResults: Error: 'SIO_TLS' is not defined, evaluates to 0 [-Werror,-Wundef]
PackagingResults: Error: 'SIO_TLS' is not defined, evaluates to 0 [-Werror,-Wundef]
PackagingResults: Error: 'DEBUG' is not defined, evaluates to 0 [-Werror,-Wundef]
PackagingResults: Error: '_DEBUG' is not defined, evaluates to 0 [-Werror,-Wundef]
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)): BUILD FAILED: Command failed (Result:1): I:\Program Files (x86)\Incredibuild\xgConsole.exe "C:\Users\mspcb\AppData\Roaming\Unreal Engine\AutomationTool\Logs\G+Epic+Games+Epic+Games+UE_4.26\UAT_XGE.xml" /Rebuild /NoLogo /ShowAgent /ShowTime /no_watchdog_thread. See logfile for details: 'xgConsole-2021.07.1
6-09.47.11.txt'
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)): AutomationTool exiting with ExitCode=1 (Error_Unknown)
UATHelper: Packaging (Android (Multi:ASTC,DXT,ETC2)): BUILD FAILED
PackagingResults: Error: Unknown Error

**Comment by getnamo** [comment]
related to https://github.com/getnamo/socketio-client-ue4/issues/271. Rollback to 1.5.5 if appropriate until fix
