### ISSUE TITLE
Cant connect to server from ue4 project client (socket-client-example-ue4)

### ISSUE THREAD

**Issue by jdc711** [getnamo/socketio-client-ue4#276]
Hi, I downloaded the example project and followed all of your steps to run it, but when I press play from the ue4 client project,   connection message is not emitted to the server (I dont think connection is successfully created). Also, nothing is emitted to the server when I press 'm'. Only connecting to the server with the Webclient (on browser) shortcut worked and produced output in the server. Do you have any suggestions as to why my ue4 client project doesnt connect with the server?

**Comment by getnamo** [comment]
Check socket.io version of your server, if its v2 or older user https://github.com/getnamo/socketio-client-ue4/releases/tag/1.5.5 if its v3 or newer use https://github.com/getnamo/socketio-client-ue4/releases/tag/1.6.0

**Comment by getnamo** [comment]
marketplace update for v3+ support is still pending

**Comment by jdc711** [comment]
How can I check the socket.io version of my server?

**Comment by getnamo** [comment]
if you're using node backend ```npm list``` or check your package.json

**Comment by getnamo** [comment]
Also see https://github.com/getnamo/socketio-client-ue4-example/releases for paired releases that are confirmed working

**Comment by jdc711** [comment]
Thanks for your help so far. I tried the 1.5.5 pair release and followed the same steps, but I got these compile errors:
Failed to load /Script/SocketIOClient.SocketIOClientComponent Referenced by K2Node_VariableGet_27
Failed to load /Script/SocketIOClient.SocketIOClientComponent Referenced by K2Node_CallFunction_68
Failed to load /Script/SIOJson.SIOJsonValue Referenced by K2Node_CallFunction_68
Failed to load /Script/SIOJson.SIOJLibrary Referenced by K2Node_CallFunction_3116
Failed to load /Script/SIOJson.Default__SIOJLibrary Referenced by K2Node_CallFunction_3116
Failed to load /Script/SIOJson.SIOJsonValue Referenced by K2Node_CallFunction_3116
Failed to load /Script/SocketIOClient.SocketIOClientComponent Referenced by K2Node_VariableGet_40
Failed to load /Script/SIOJson.SIOJsonValue Referenced by K2Node_CallFunction_135
Failed to load /Script/SocketIOClient.SocketIOClientComponent Referenced by K2Node_VariableGet_51
Failed to load /Script/SocketIOClient.SocketIOClientComponent Referenced by K2Node_CallFunction_149
Failed to load /Script/SIOJson.SIOJsonValue Referenced by K2Node_CallFunction_149
Failed to load /Script/SIOJson.SIOJLibrary Referenced by K2Node_CallFunction_3124
Failed to load /Script/SIOJson.Default__SIOJLibrary Referenced by K2Node_CallFunction_3124
Failed to load /Script/SIOJson.SIOJsonValue Referenced by K2Node_CallFunction_3124
Failed to load /Script/SocketIOClient.SocketIOClientComponent Referenced by K2Node_CallFunction_129
Failed to load /Script/SocketIOClient.ESIOThreadOverrideOption Referenced by K2Node_CallFunction_129
Failed to load /Script/SocketIOClient.SocketIOClientComponent Referenced by K2Node_CallFunction_0
Failed to load /Script/SocketIOClient.SocketIOClientComponent Referenced by K2Node_ComponentBoundEvent_1
Failed to load /Script/SocketIOClient Referenced by K2Node_ComponentBoundEvent_1
Failed to load /Script/SIOJson.SIOJsonValue Referenced by K2Node_ComponentBoundEvent_1
Failed to load /Script/SIOJson.SIOJsonValue Referenced by K2Node_FunctionEntry_14
Failed to load /Script/SIOJson.SIOJsonValue Referenced by K2Node_CallFunction_89
Failed to load /Script/SocketIOClient.SocketIOClientComponent Referenced by SCS_Node_3

**Comment by getnamo** [comment]
Ensure you're using the .7z file from releases and not zip or tar.gz

**Comment by jdc711** [comment]
I am trying that right now. Just making sure, 0.2.0 for server version means v2, right?

**Comment by jdc711** [comment]
Using .7z did the trick! Thanks for your prompt feedback and support. Cheers!
