### ISSUE TITLE
Acknowledgement to Server?

### ISSUE THREAD

**Issue by bingqiao** [getnamo/socketio-client-ue4#283]
Is there a way to acknowledge a server emit?

What I'm trying to achieve is to have a nodejs restful endpoint that:
1) accepts a http request with valueA;
1) emits valueA to UE client, with a callback to handle acknowledgement;
2) the UE client handles this event via socketio-client-ue4, then acknowledges valueA with valueB;
3) the nodejs service endpoint receives valueB in the callback then sends it back to the http client.

Thank you

**Comment by getnamo** [comment]
See https://github.com/getnamo/socketio-client-ue4/issues/79. There also is an old solution from HeffU there you may want to look at, but it might not work as expected.

General problem is that the current sio lib architecture expects an ack immediately on the network thread which can't be done if you're responding to things in the game thread on the unreal side. It's likely a re-architecture is needed for that part to support server emit ack. The obvious work around is to use 2 events with a unique id, that just isn't a very clean solution.
