### ISSUE TITLE
Linux Case Sensitivity Issue

### ISSUE THREAD

**Issue by maiconpintoabreu** [getnamo/socketio-client-ue4#288]
Sorry for my English in advance.
Hi, I was having a issue on when I was trying to package my project for Linux and I was having a issue with linux case sensitivity on the file: https://github.com/getnamo/socketio-client-ue4/edit/ue5/Source/CoreUtility/Private/CUFileComponent.cpp trying to import #include "HAL/PlatformFilemanager.h", that is btw renamed on UE5.

Suggested fix:

Line:5
Fix: PlatformFilemanager.h ->PlatformFileManager.h

**Comment by getnamo** [comment]
Looks like the current naming is the correct one according to https://docs.unrealengine.com/4.26/en-US/API/Runtime/Core/HAL/FPlatformFileManager/ and https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Source/Runtime/Core/Public/HAL/PlatformFilemanager.h
