### ISSUE TITLE
It works fine in the editor mode, but cannot connect to the server in the packaged project. Anyone know why?

### ISSUE THREAD

**Issue by Akun9527** [getnamo/socketio-client-ue4#289]
Engine version:4.23.1

I tried package the project in win64 or H5 format. But neither can access the server. I am new to ue4, anyone know where should I look into? 

I also test the demo project, and it wont work in H5 or win64 packaged. Anyone knows why?

And I had this error message while I try to send some text to server in H5 packaged demo

Uncaught abort(197) at Error at jsStackTrace (blob:http://localhost:8000/5e15bb10-28ae-49c2-be41-4a240a3f7fd4:654:12) at stackTrace (blob:http://localhost:8000/5e15bb10-28ae-49c2-be41-4a240a3f7fd4:669:11) at abort (blob:http://localhost:8000/5e15bb10-28ae-49c2-be41-4a240a3f7fd4:21005:43) at nullFunc_viii (blob:http://localhost:8000/5e15bb10-28ae-49c2-be41-4a240a3f7fd4:17194:2) at b197 (wasm://wasm/14a99e4e:wasm-function[127754]:0x3af1ade) at UObject::execCallMathFunction(UObject*, FFrame&, void*) [__ZN7UObject20execCallMathFunctionEPS_R6FFramePv] (wasm://wasm/14a99e4e:wasm-function[12029]:0x5f66c1) at UObject::execLetObj(UObject*, FFrame&, void*) [__ZN7UObject10execLetObjEPS_R6FFramePv] (wasm://wasm/14a99e4e:wasm-function[12051]:0x5fbf3b) at ProcessLocalScriptFunction(UObject*, FFrame&, void*) [__Z26ProcessLocalScriptFunctionP7UObjectR6FFramePv] (wasm://wasm/14a99e4e:wasm-function[12160]:0x60a56e) at void ProcessScriptFunction(UObject*, UFunction*, FFrame&, void*, void (*)(UObject*, FFrame&, void*)) [__Z21ProcessScriptFunctionIPFvP7UObjectR6FFramePvEEvS1_P9UFunctionS3_S4_T_] (wasm://wasm/14a99e4e:wasm-function[12161]:0x60b504) at ProcessLocalFunction(UObject*, UFunction*, FFrame&, void*) [__Z20ProcessLocalFunctionP7UObjectP9UFunctionR6FFramePv] (wasm://wasm/14a99e4e:wasm-function[12159]:0x60972a)

**Comment by getnamo** [comment]
Can you try a newer version of the plugin/engine (e.g. 4.27) and let me know if the problem persists?

**Comment by Lostonelzq** [comment]
Yes, I just tried. It's a real problem.You can connect by typing your address from the web page.UE4 cannot be connected.And no logs were printed.And Why is the third-party library empty when github pulls files？

**Comment by Akun9527** [comment]
> Can you try a newer version of the plugin/engine (e.g. 4.27) and let me know if the problem persists?

Since Unreal Engine 4.24, support for the HTML5 platform has been migrated out of the engine to a public Platform Extension that can be maintained and improved by community members.  Currently this github repo[https://github.com/UnrealEngineHTML5/Documentation](url) only support 4.25

**Comment by getnamo** [comment]
HTML5 platform isn't supported see https://github.com/getnamo/socketio-client-ue4/issues/94. There isnt a clear path to add code plugins with third party libraries for the html platform.

Closing as duplicate, continue support discussion there
