### ISSUE TITLE
SIOJson not found.

### ISSUE THREAD

**Issue by Thomas-R-dev** [getnamo/socketio-client-ue4#292]
is it normal ?

i get this error when i build the project :(

![Capture d’écran 2021-12-11 104508](https://user-images.githubusercontent.com/20694389/145716986-2939dca6-21e1-445f-97de-4596178f9ded.jpg)

**Comment by getnamo** [comment]
How did you get the plugin (clone or release?)? What version? are you using Bp or C++ project?

**Comment by Thomas-R-dev** [comment]
Yes , Release 1.8.0 7z file , i use only BP. My UE is 4.27.2
I try to build Windows x64

**Comment by getnamo** [comment]
See https://github.com/getnamo/socketio-client-ue4#packaging, specifically https://github.com/getnamo/socketio-client-ue4#github if you're using github releases.

**Comment by Thomas-R-dev** [comment]
Thanks it's works :)
i use a lot of plugins without C++ Project , it's weird xD

**Comment by getnamo** [comment]
Code plugins have that quirk unless they're already included in engine via e.g. marketplace.
