### ISSUE TITLE
get field array is not pulling my data

### ISSUE THREAD

**Issue by mazlum1414** [getnamo/socketio-client-ue4#296]
hello, I am pulling my data to my server using mysql database, but I want to pull my data as in varest plugin, but the result is always zero can anyone help?

**Comment by mazlum1414** [comment]
![Adsız](https://user-images.githubusercontent.com/83881717/146875726-29f3e575-c859-4a7d-92da-a0495605769a.png)

**Comment by mazlum1414** [comment]
@getnamo please :(

**Comment by getnamo** [comment]
Looks like your initial reply is not an object but an SIOJsonArrayValue

**Comment by mazlum1414** [comment]
> Looks like your initial reply is not an object but an SIOJsonArrayValue
![Adsız](https://user-images.githubusercontent.com/83881717/147033222-7ac7babd-d820-4b40-bea2-ba98d641958d.png)
thenks fix

**Comment by mazlum1414** [comment]
> Looks like your initial reply is not an object but an SIOJsonArrayValue

hello, thanks for your reply, i have taken care of it, is there a way to parse the string, i am giving a sample picture
![Adsız](https://user-images.githubusercontent.com/83881717/147033415-3bfe303e-89f3-42e4-b239-509778afac57.png)

**Comment by getnamo** [comment]
See https://github.com/getnamo/socketio-client-ue4#decoding-responses for decode methods

**Comment by mazlum1414** [comment]
> See https://github.com/getnamo/socketio-client-ue4#decoding-responses for decode methods

{
    "ID": 1,
    "Name": "Sunucu 1 MTN3",
    "Region": "Tr",
    "Online": "12",
    "Slot": "100",
    "Port": "2010",
    "ServerİP": "127.0.0.1"
  }

hello, I looked there, but I couldn't succeed what I did, can you give me an example if possible? I give an example: I want to pull the port of server 1 MTN3 I can convert it to json with as string, but there is no substring specifier of astring in the plugin.

**Comment by mazlum1414** [comment]
You can understand better from the picture above what I mean.

**Comment by getnamo** [comment]
If you use 'as string' node on your siojsonvalue and then print it out what do you get?

I believe you need to cast value to array not object, then get object in array e.g. at 0 and then decode that object

**Comment by mazlum1414** [comment]
> If you use 'as string' node on your siojsonvalue and then print it out what do you get?
> 
> I believe you need to cast value to array not object, then get object in array e.g. at 0 and then decode that object
![Adsız](https://user-images.githubusercontent.com/83881717/147202684-3e3fc4f8-c45f-4239-b446-2d9b74e5c863.png)
![Adsıfz](https://user-images.githubusercontent.com/83881717/147202687-0c535389-86be-45fc-95b8-cb64ca5a894b.png)

**Comment by mazlum1414** [comment]
I want me to shoot this with array

**Comment by mazlum1414** [comment]
> If you use 'as string' node on your siojsonvalue and then print it out what do you get?
> 
> I believe you need to cast value to array not object, then get object in array e.g. at 0 and then decode that object

hello, also the emit parse feature is not working

index.js cod :
	socket.on('saveplayer',function(data){
	console.log(data.nick);
});


![Adsız](https://user-images.githubusercontent.com/83881717/147240585-0a67a2cb-aa2b-4ff4-8c8f-0d8a918d0a23.png)


![Agfdsız](https://user-images.githubusercontent.com/83881717/147240652-0673ab1c-c899-417d-a59c-19b3048a268a.png)

**Comment by mazlum1414** [comment]
Am I sending wrong information?

**Comment by getnamo** [comment]
Yep that confirms that you're sending an array of objects, you need to cast your message as array then get index 0 value then that is your object you can decide as expected

**Comment by mazlum1414** [comment]
> Yep that confirms that you're sending an array of objects, you need to decode your message as array of siojson values then get index 0 value then that is your object value which you can decode as expected earlier via get fields (or optionally auto struct conversion)

okey thenks :)
