### ISSUE TITLE
Receive data from Socket to update widget at runtime.

### ISSUE THREAD

**Issue by SleepyOwl15** [getnamo/socketio-client-ue4#299]
Hello! I'm currently using the socket.io client and its amazing!
thank you for your contribution.

I would like to ask some question and some advice regarding a project I'm working on.

Currently I'm making a VR space that can receive data information from IoTs to display in real time.
By using socket IO, every time the data is updated. i would like my widget to change its displayed data.

I have gone through the steps of getting the value from my json object and print out values that i need.
however, when i try to use the data to set a variable, cast to widget to update the data. it does not update and stays at default value.

I'm very new to unreal and wonder if there's any particular subject i need to look on for this work around or for this particular issue what should i use from the socket.io plugin. Blueprints for each element is posted below. many thanks!

**My Blueprints**

![toStructWorking](https://user-images.githubusercontent.com/15926511/148914069-9939d812-e628-43ab-8cc2-3b15263a74b6.PNG)

> my widget blueprint which includes the socket io component. push string to struct and for dev i print out 1 of  the values and as you can see the value is printed properly

![dataformat](https://user-images.githubusercontent.com/15926511/148914659-b40f3c33-4056-488f-b042-8852c86c8c02.PNG)

> data format for reference

![ValueStruct](https://user-images.githubusercontent.com/15926511/148914740-e6852013-54f2-43fa-9980-92b1676cc492.PNG)

> my struct values

![widgetblueprint](https://user-images.githubusercontent.com/15926511/148914866-fd87a477-0e89-435b-b8f9-4f44f1ed2b43.PNG)

> my widget blueprint

![Struct working as intended](https://user-images.githubusercontent.com/15926511/148914825-4433d0fb-fdaa-4181-9fc8-93e08ecb6a42.PNG)

> try change default values from struct. working as intended

![valueupdatenochage](https://user-images.githubusercontent.com/15926511/148914958-476b5c13-aaac-4671-8213-93b4f1e9d8d8.PNG)

> as seen on top right, new value has been print but no update on widget

thank you in advance.

**Comment by SleepyOwl15** [comment]
I got it!
looking through the chat project examples.  i realized what i have to do is bind the values to function and cast to the widget.
this way instead of hooking to the variables directly which will end up always pulling the default value, it will display the received data from web socket.

What my blue print ended up look like 

> by looking through the chat example project i set up a similar receive function to be able to print on widget. first by setting up a function to link the blueprint with the widget using casting. 

![bp1_eventbeginplay](https://user-images.githubusercontent.com/15926511/149700659-d9a0b543-e59d-41bc-9320-cc872b622dba.PNG)

> cast to widget with get user widget so we can promote it as a variable, pulling in a function in the next step.

![casttowidget](https://user-images.githubusercontent.com/15926511/149700667-48b038dc-db57-487d-82b4-9e7b54726ee6.PNG)

> I also make another function that is binded to socket. where the data will be received (the same as the example project)
which then will be forwarded to another function create inside the widget
![receiveiaqstatus](https://user-images.githubusercontent.com/15926511/149700887-da1b2d4c-9f9e-4187-94f2-33c28d4f4de2.PNG)

> inside the widget a function is create to receive all of the data sent.
![statusreceived](https://user-images.githubusercontent.com/15926511/149700961-40e0e39c-6736-4ab7-bd8c-db1ded829f75.PNG)

and it works!

as for the pictures displayed on the right I use material instance along with a custom material switch on int found here. https://answers.unrealengine.com/questions/864110/switch-on-int-for-materials-scalarsgrayscale-textu.html

> my material setups which will be changed according to the int received from the json
![texturematerialinstance](https://user-images.githubusercontent.com/15926511/149701030-6902c7ca-4645-4a67-b9e8-9a8ee290ca6f.PNG)

> inside the very same function use to receive the data, the int received is forwarded to the material instance to tell unreal which instance to show
![materialswitchparam](https://user-images.githubusercontent.com/15926511/149701133-645d52f0-bc5a-4c42-b10d-c98e2ff0716f.PNG)

> then creating material instance in event begin play so the image is properly displayed, along with binding the material with a function so it changes properly.

![creatematerial](https://user-images.githubusercontent.com/15926511/149701209-2ef1812f-52e4-497c-8d5e-42317eca4640.PNG)
![materialswitchparam](https://user-images.githubusercontent.com/15926511/149701212-ceac882f-52f0-4400-a84f-65a12fa764b3.PNG)
![setmaterial](https://user-images.githubusercontent.com/15926511/149701215-db8de78c-2431-433a-9cdd-33807bca1352.PNG)

for now ill stick with this! if theres a better way or if there are suggestion it will help me alot! thank you!

**Comment by getnamo** [comment]
Your updated version seems correct. The older method shouldve worked as well if you had the same member struct references in both read and write; you might've accidentally used a local struct instead for write.
