### ISSUE TITLE
Multiple bind event to function not firing

### ISSUE THREAD

**Issue by oandreassen** [getnamo/socketio-client-ue4#34]
![image](https://cloud.githubusercontent.com/assets/5681202/24134018/c3718f98-0e01-11e7-9bb8-1a2039125322.png)

Binding twice to the same event name does not fire second time.

**Comment by getnamo** [comment]
I believe this is by design unless I'm missing something. The action of binding an event to a functions sets and replaces any previous callback function for that event. If you wish to multicast the event to multiple functions, consider forwarding from the bound function.
