### ISSUE TITLE
Get Bool field always returns false.

### ISSUE THREAD

**Issue by oandreassen** [getnamo/socketio-client-ue4#35]
![image](https://cloud.githubusercontent.com/assets/5681202/24203564/67951d5a-0f16-11e7-9cca-38e3158ca11f.png)

If value is passed as 
`
{
"isConnecting" : true
}
`

GetBoolField returns false.

If the value is passed as a string instead
`
{
"isConnecting" : "true"
}
`

then GetStringField returns "true" as expected.

**Comment by getnamo** [comment]
Interesting, I'll have a look at this when I'm back in a few days

**Comment by getnamo** [comment]
fixed in https://github.com/getnamo/socketio-client-ue4/releases/tag/0.5.2.

This one was a derp, left a boolean = false by default before linking it to the raw message pointer data as I started fleshing out the conversion utility class and then I totally forgot about booleans  ¯\\\_(ツ)_/¯
