### ISSUE TITLE
Additional headers on connect

### ISSUE THREAD

**Issue by oandreassen** [getnamo/socketio-client-ue4#40]
It would be great if you could pass additional HTTP headers when connecting - for example, passing OAUTH-tokens to authenticate on the server.

**Comment by getnamo** [comment]
If it's something supported by https://socket.io/docs/client-api/ and https://socket.io/docs/server-api/ then give me an example of expected behavior for what you mean from both sides (server and client)

**Comment by oandreassen** [comment]
From our Socket.IO Server:
`
   public use(server: SocketIO.Server): void {
        let self = this;

        this._namespace = server.use(this.onRequest.bind(this));
    /// ...
    }

private onRequest(socket: SocketIO.Socket, next: (error: Error) => void): void {
        let message = socket.request as IncomingMessage;

        if (message != null && message.headers['authentication']) {
            let auth = message.headers['authentication'] as string;

            if (auth == null || typeof (auth) != 'string') {
                done(new RequestError(400, 'Authentication header value was null or not a string.'));
            } else {
               // .. parse header
        }
    }
`

**Comment by getnamo** [comment]
That looks like javascript, but I've never seen public/private and type specifiers on it, TypeScript?

**Comment by oandreassen** [comment]
Yes sir! But the point is, socket.io have a server.use method which can be used to authenticate incoming calls. I would like to refer you to the socket.io documentation but its sooo limited. There are however a number of authentication npm-packages for socket.io which uses this approach as well.

**Comment by getnamo** [comment]
It looks like the client api has a callback on connection https://socket.io/docs/client-api/#manager-open-callback where you could then call the servier with the auth information and then let the server accept/reject. I guess what I'm saying is, we'd need an example on the client side of how this is handled. I'm guessing the OAuth token/etc would be a json object we'd pass in at the right point somewhere.

**Comment by oandreassen** [comment]
We dont actually use any callback here, its just a additional header that is passed upon connect. If the authentication fails the client is disconnected - there is no additional work on the client side.

**Comment by getnamo** [comment]
Ok so we might be in luck, maybe. While https://socket.io/docs/client-api/ doesn't have anything about headers, there is this overload on connect https://github.com/socketio/socket.io-client-cpp/blob/master/src/sio_client.h#L61 which was pulled into socket.io-cpp master "recently" https://github.com/socketio/socket.io-client-cpp/commit/cda7b205dcc6d5db6f421d0eb57b4893ea6ad9f6 and with 0.5.0 I did update the underlying library to sync with master which added that API https://github.com/getnamo/socketio-client-ue4/commit/1af67eb2dc7e4de4d9ee6ac6846c634ccffdc071#diff-bbdab768c8bada5381ddc3001a2bb126R61.

To try the method, we would need to expose that connect method as an overload and try it out. The headers seem to be structured as a string:string keyed object. For UE4 api I'm thinking we could expose a blueprint connect function taking a SIOJson object with the understanding that it should be String:String keyed.

Thoughts? Is this what you're looking for?

**Comment by oandreassen** [comment]
@getnamo thats exactly what I'm looking for

**Comment by getnamo** [comment]
latest merge https://github.com/getnamo/socketio-client-ue4/commit/f84af8c3a0bc02a957a05700c7c2cf7b51418cf9 (0.5.4) exposes the query and headers field as optional settings for Connect.

They expect  an empty field by default _(nullptr in c++)_ or a _SIOJsonObject_ with purely string fields.

Here's an example of a connect call with a single header _X-Forwarded-Host: qnova.io_ (remember to toggle auto-connect off in the component)
![connectwithheader](https://cloud.githubusercontent.com/assets/542365/25309683/63bfe26e-27cb-11e7-877e-0590e40605f3.PNG)

I can inspect this header being passed by using the socket from _io.on('connection')_ via [socket.conn](https://socket.io/docs/server-api/#socket-conn) and then digging down the tree in the object being passed

![image](https://cloud.githubusercontent.com/assets/542365/25309715/1c31e9c8-27cc-11e7-92bf-7fb0eae31523.png)

which resulted in

![image](https://cloud.githubusercontent.com/assets/542365/25309708/faea29b0-27cb-11e7-9514-06f0cbf73448.png)

from the server console, so it should be working. Have a go with 0.5.4 and let me know if it's working as intended; though you'll have to recompile from source right now as I'm going to wait until I've addressed the new connection issues before making a new release.

**Comment by getnamo** [comment]
add complex connect blueprint section

**Comment by getnamo** [comment]
documentation added under: https://github.com/getnamo/socketio-client-ue4#complex-connect

**Comment by oandreassen** [comment]
Thank you very much! Keep up the awesome work!11!
