### ISSUE TITLE
Invalid module name while checking availability

### ISSUE THREAD

**Issue by nomako** [getnamo/socketio-client-ue4#46]
Why you need to check for **LeapMotionC** if your module called **SocketIOClient**?

[SocketIOClient.h](https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SocketIOClient/Public/SocketIOClient.h#L30)
```cpp
...
	static inline ISocketIOClientModule& Get()
	{
		return FModuleManager::LoadModuleChecked< ISocketIOClientModule >("SocketIOClient");
	}

	static inline bool IsAvailable()
	{
		return FModuleManager::Get().IsModuleLoaded("LeapMotionC");
	}
...
```

**Comment by getnamo** [comment]
That's a bug, this will make is available fail each time. Feel free to make a pull request
