### ISSUE TITLE
Strange behavior with SocketIOComponent::UninitializeComponent()

### ISSUE THREAD

**Issue by nomako** [getnamo/socketio-client-ue4#48]
I found some strange behavior with SocketIOComponent deinitialization process.
I logged calls of **InitializeComponent()** and **UninitializeComponent()** of **SocketIOComponent** and almost everytime on one **Init** call there were two **Uninit** calls.

In my project sometimes it leads to crash game with "Fatal error" exception message box.

In function below **bIsConnected** is always true (with successfull connection with server)  in both **Uninit** calls so **Super::UninitializeComponent()** is never being called.

I think second call is from GC, coz Component wasn't unitialized properly.

[SocketIOClientComponent.cpp](https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SocketIOClient/Private/SocketIOClientComponent.cpp#L32)
```cpp
void USocketIOClientComponent::UninitializeComponent()
{
	//This may lock up so run it on a background thread
	if (bAsyncQuitDisconnect)
	{
		if (bIsConnected)
		{
			FSIOLambdaRunnable::RunLambdaOnBackGroundThread([&]
			{
				FScopeLock lock(&AllocationSection);
				NativeClient = nullptr;
			});
			return;
		}
	}
	else
	{
		FScopeLock lock(&AllocationSection);
		NativeClient = nullptr;;
	}

	Super::UninitializeComponent();
}
```

**Comment by getnamo** [comment]
Excellent spot, it should just need a super call before the return. Feel free to open a pull request, if not I'll get it on my next plugin pass.

**Comment by getnamo** [comment]
fix merged in https://github.com/getnamo/socketio-client-ue4/commit/2fa439999f2ca099f41a40d3c798bd0e4724b0c2
