### ISSUE TITLE
Failing to find 'SIOJson'

### ISSUE THREAD

**Issue by eztain** [getnamo/socketio-client-ue4#54]
I have installed socketio-client-ue4 to the plugins file of my project. I have nodejs installed, I have socket.io installed. I am still getting this error [(Screencap)](https://i.gyazo.com/109a6c70b1fa5b78425d6649ed72fa51.png) I have scoured the Github but could not find anything about dependencies.

I am running windows 10 x64 
I am running Unreal Engine 4.16.2 (I have also tried 4.16.1) 
I have the latest installs (as of the time of this post) of Nodejs and Socket.io as well as the socket.io plugin.

**Comment by getnamo** [comment]
Sounds like SIOJson module is disabled in your context. Did you download the latest release binaries or recompile the plugin from c++?

**Comment by eztain** [comment]
I downloaded them this github

**Comment by getnamo** [comment]
Did you select source or the .7z archive from https://github.com/getnamo/socketio-client-ue4/releases/tag/0.6.2 ? The correct download is  socketio-client-v0.6.2-UE4.16.7z which contains compiled .DLLs for 4.16. otherwise you need to take the source of the plugin and recompile it in a c++ project.

**Comment by eztain** [comment]
That fixed it thanks.
