### ISSUE TITLE
Seperate Branches for each unreal version

### ISSUE THREAD

**Issue by cpyarger** [getnamo/socketio-client-ue4#58]
I recommend setting up separate branches, that allow for branch specific fixes to be implemented and for people to easily access the code for each branch if needed.

**Comment by getnamo** [comment]
I used to do this in the past in [other plugins](https://github.com/getnamo/hydra-ue4/branches), but those branches were never used, so I stopped as it was too much maintenance work. That said, each [binary release](https://github.com/getnamo/socketio-client-ue4/releases) is tagged with a commit such that if you want an older branch you can fork from that tag and incorporate fixes you're interested in, if any such fork becomes popular I can incorporate it into a branch, which I think is a good balance between time and usefulness.

**Comment by cpyarger** [comment]
Sounds good and makes sense.
