### ISSUE TITLE
An fatal error occurs after packaging

### ISSUE THREAD

**Issue by nupamore** [getnamo/socketio-client-ue4#62]
There is nothing wrong with playing in the engine. But an fatal error occurs after packaging like this.

```
Fatal error:
[File:D:\Build\++UE4+Release-4.17+Compile\Sync\Engine\Source\Runtime\CoreUObject\Private\Serialization\AsyncLoading.cpp][Line:3004]
Missing Dependency, request for SocketIOClientComponent but it hasn't been created yet.
```

I was only trying to connect in a clean project. 4.16 and 4.17.  
So I put the plugin in a packaged folder.
Then I saw this.

```
Plugin 'SocketIOClient' faild to load because module 'SIOJson' could not be found.
Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project.
```

Could you tell me the solution?

**Comment by getnamo** [comment]
Maybe 4.17 changed how packaging with dependencies works, try changing https://github.com/getnamo/socketio-client-ue4/blob/master/SocketIOClient.uplugin#L32 to ```Default``` and recompile

**Comment by nupamore** [comment]
Rebuild then solved thanks!
