### ISSUE TITLE
Json Object to Struct not work?

### ISSUE THREAD

**Issue by DantaliaN00** [getnamo/socketio-client-ue4#67]
Question in title.

Steps:
- Construct Json Object (new)
- Decode Json from string or set string field
- check fill by encode json - correct
- Make empty Struct with correct fields
- try Json Object to Struct (return true)
- check by break struct or struct to json - values is empty

But Struct to Json works correctly

![image](https://user-images.githubusercontent.com/1700620/34108262-7b44b73c-e410-11e7-9e4a-593e9c25895f.png)

Any thoughts?

**Comment by DantaliaN00** [comment]
My bad. I make a new struct, but I'll need to create new Variable and change it

![image](https://user-images.githubusercontent.com/1700620/34130946-da3149fa-e45a-11e7-96b6-cd445df3aa29.png)

**Comment by getnamo** [comment]
Your answer is correct. You need a variable (local or member) containing a compatible struct which the function fills by reference. In your first graph, the 'make' struct node should always contain the initialized struct with specified default values, if you want those struct values to change it will need to be set to a local or member variable.
