### ISSUE TITLE
Packaging don't work

### ISSUE THREAD

**Issue by Monstreur** [getnamo/socketio-client-ue4#68]
Hi !
When i launch my project into UE4: all is working, the client is connected to my server, etc.
But when i packaged my project (for win64). Nothing with this plugin work. Is there something needed to be activated ?

**Comment by getnamo** [comment]
Are you trying to package a blueprint only project? This doesn't work with purely project plugins in unreal engine. To fix it, convert your project to support C++ by adding a simple empty C++ class file in File->New C++ class and recompile (see e.g. https://allarsblog.com/2015/11/04/converting-bp-project-to-cpp/ for details). After that it should package correctly

**Comment by getnamo** [comment]
When packaging, UE4 collapses all plugins into a monolithic .exe which is why it requires the project to be C++ to detect the plugins to recompile as .libs instead of .dlls.

**Comment by Monstreur** [comment]
It works now! Thanks :D !!
Do I need to build every time I change something in my project (even if it's only in blueprint) ?

**Comment by getnamo** [comment]
Nope, this only needs to be done once per engine build (e.g. will need a recompile when 4.19 comes out and you switch to it), otherwise your project will behave as usual. Also with the project being C++ it will package plugin dependencies correctly even if you update the source.

**Comment by Monstreur** [comment]
This was just for create .lib files ?

**Comment by getnamo** [comment]
Converting a project to C++ and compiling will add a ```UE4Editor-<yourprojectname>.dll``` in your ```<project root>/Binaries/Win64``` folder. Then when you package, the editor will recompile all your modules as .lib files which get included in the final .exe file in your packaged folder.

Decided to add a small section to the readme about packaging for future users here: https://github.com/getnamo/socketio-client-ue4/blob/master/README.md#packaging
