### ISSUE TITLE
Crash after first emit

### ISSUE THREAD

**Issue by helldog136** [getnamo/socketio-client-ue4#71]
Hi,

for my project I send a message every 0.5 seconds by using a timer and every time i launch the application, it crashes after sucessfuly sending the first message and i can't figure out why. 

here are the logs of the application
[VIVENAOControl.log](https://github.com/getnamo/socketio-client-ue4/files/1716478/VIVENAOControl.log)

thanks for your help :-)

EDIT changed my Emit with a correct Emit with callback and it works now. I'm still curious about why it doesn't work with a simple Emit...

**Comment by getnamo** [comment]
It will largely depend on what you're actually doing. Do you have an example image of the blueprint graph and a code snippet of the server part?

**Comment by MykonCodes** [comment]
The crash has nothing to do with socket IO, judging by the crash log. I think this can be closed. The crash comes from inverting a NIL matrix.

**Comment by getnamo** [comment]
I believe you're correct @MykonCodes. Closing issue, if you still have the problem, provide more steps to replicate the issue, including data types sent and blueprint graphs if possible as a new issue.
