### ISSUE TITLE
Connect via URL instead of IP

### ISSUE THREAD

**Issue by MykonCodes** [getnamo/socketio-client-ue4#72]
Hey.

Currently having no success establishing a connection when using an URL as the parameter for the Connect function instead of an IP Adress. We'll be using a load balancer and therefore the IP of our servers will change. Is there any integrated way of connecting to an URL instead?

All the best,
Mykon

**Comment by getnamo** [comment]
This already works, e.g. https://github.com/getnamo/tensorflow-ue4-examples/blob/master/Content/ExampleAssets/Blueprints/ConnectedTFMnistActor.uasset uses ```http://qnova.io:3000``` for the address and port to support [web-based input for classification](https://github.com/getnamo/tensorflow-ue4-examples#classifying-custom-data).

Just make sure you specify both url and port http://{your url}:{socketio port}. Default http port btw is 80.

**Comment by MykonCodes** [comment]
Thanks for the quick response, however that doesn't work for us.

The logger of the underlying socketIO impl do not output to the UE4 logs, but with manual debugging I found the error code being "pass_through - Underlying Transport Error". No clue what that means. Tried it with port, without, with leading http:// and https:// and without. And those IP's that do work resolve to the exact same IP's. JS SocketIO has no issue connecting to the same URL's.

**Comment by getnamo** [comment]
NB: http**s** isn't currently supported see https://github.com/getnamo/socketio-client-ue4/issues/39. Make sure you're not using SSL

**Comment by MykonCodes** [comment]
I just tested with it, we don't require https. How would I make sure SSL is not used? Sorry, completely knew in this SocketIO / Websocket stuff

**Comment by getnamo** [comment]
Have you tried a url at the root domain? e.g. like ```http://qnova.io:3000``` I haven't personally figured out how to get the **path** option to work with servers (https://socket.io/docs/server-api/#new-server-httpserver-options) we might need a to handle path in a special way on connection like the javascript client does in the ```io([url],[options])``` function (https://socket.io/docs/client-api/#io-url-options)

We'd could use a working minimal example of a server with path and javascript client with path to see what's missing in the c++ client.

**Comment by MykonCodes** [comment]
Sorry that I didn't respond, had some other issues to work on. And I was being stupid, sorry for that, we indeed use HTTPS. Now I am 99% sure I tested on non-https too, but maybe I had a typo or something, I don't know, at least non https URL's now work, but yeah.. Really need HTTPS to work. So I'll look into how to enable it.

**Comment by MykonCodes** [comment]
So I spend the whole day trying to get OpenSSL working, and it is a total pain in the ***. To get everything running for a x64 machine. Eventually I tried 5 different versions of socket io cpp, got OpenSSL integrated and UE4 starting up 2 times, but only to find out that now no IP or URL at all works anymore..

**Comment by MykonCodes** [comment]
My current run is using your prebuild repository, where I had to tweak a ton already to make CMake build with OpenSSL and find the proper boost libs, but yeah... When I bind the sioclient_tls.lib, it just doesn't work.. Spits out ITERATOR_DEBUG_LEVEL mismatches when I try to use the debug build, so I can't debug it either..

**Comment by getnamo** [comment]
It's awesome to have another pair of eyes on getting this set up. Getting everything to splice even for the regular non-ssl version was always a day affair for me and I'm frankly a noob at cmake. If you get a working build, consider making a pull request on prebuild and here.

Regarding TLS, Have you had a look at these two issues 

https://github.com/socketio/socket.io-client-cpp/issues/13
and 
https://github.com/socketio/socket.io-client-cpp/issues/46?

First issue should point at code changes that were needed for TLS work with socket.io and issue 46 points to needing a macro define for things to compile. Other than that you can still run UE4 in debug mode while having release libraries linked which may hint at where the issue may lie even if the lib code is not all exposed.

**Comment by MykonCodes** [comment]
Got it working. It required a ton of cheat-arounds though and god do I hate CMake. Same goes for me, I know the basics of it but I want to vomit each time I have to use it :P

I'll see if I can figure out a way to do a pull request, however I noticed that connections to normal HTTP servers don't work anymore with TLS enabled. I can share the code privatly with you first if you also want to have a look on how to use TLS only when applicable.

**Comment by getnamo** [comment]
I'd be definitely interested in the build configs changed for ssl and working prebuilt libraries (.lib). Even if it is a trade off atm it would get us closer to getting a full solution. What I've done is open a new branch called ```windows-ssl``` on the prebuild here https://github.com/getnamo/socketio-client-ue4/tree/windows-ssl and if you make a pull there we will have it for reference when trying to get a holistic solution.

**Comment by MykonCodes** [comment]
Alright, I will see if I can get anything useful together. Issue here is I have around 5-6 sioclient projects on my PC now and I think I even had to use a special version of the websocketpp repo. If I create a pull request I at least want it to be somewhat useable and approved, so it might take me a bit. Also, you created the branch on the plugin, not the prebuild. :)

**Comment by getnamo** [comment]
Whoops :)! here's the new branch https://github.com/getnamo/socketio-client-prebuild/tree/windows-ssl

Note that the pre-build uses submodules: https://github.com/getnamo/socketio-client-prebuild/tree/windows-ssl/src which then depends on submodules: https://github.com/getnamo/socket.io-client-cpp/tree/bfa0a53a4851cbbd56d4606c6d6fbed3f81a964b/lib so you can also add pull requests there to update the websocket library and it will all be contained :) (made a branch there too: https://github.com/getnamo/socket.io-client-cpp/tree/ssl-fixes)

**Comment by MykonCodes** [comment]
As I currently have a ton to do, for now I zipped up the socket io cpp folder with the cmake files and everything. https://www.dropbox.com/s/rukc165a0uj91m1/socket.io-client-cpp.zip?dl=0

I also had to make TLS to use the OpenSSL of UE4, so you will need to replace the reference to it in the sioclient_tls project. I think I only have the working settings in the configuration RelWithDebInfo x64. 


And here the  (messy) build.cs 
https://www.dropbox.com/s/vkknmklnuh37vaw/SocketIOClient.Build.cs?dl=0

**Comment by rastko1996** [comment]
Hey, any updates on this?

**Comment by getnamo** [comment]
The issue lies at the underlying [websocketpp](https://github.com/zaphoyd/websocketpp) library, which requires an update to support TLS and non TLS endpoints at the same time. Some movement has been made toward providing easy examples to support this here https://github.com/zaphoyd/websocketpp/issues/734 and here https://github.com/zaphoyd/websocketpp/issues/706

Once an example is available for reference in order to update https://github.com/socketio/socket.io-client-cpp we can merge that in when we recompile the library for this plugin's use.

Contributions are welcome!

**Comment by MykonCodes** [comment]
Will take a peek at that when I have the time, maybe on saturday. It's been a while since I got it working and didn't touch it since.

**Comment by Bdoom** [comment]
Why hasn't this been added to the main repo before this guys dropbox takes that script down??
