### ISSUE TITLE
Plugin Build Error in Mac 

### ISSUE THREAD

**Issue by haminjun** [getnamo/socketio-client-ue4#73]
Hello. I did add socket.io plugin to new empty project.
but I got build error at SocketIOClient.cpp.o FSocketIONative::Connect

<img width="1418" alt="default" src="https://user-images.githubusercontent.com/9061434/37522330-ea434f18-2966-11e8-8402-24524cd9d3c1.png">

version 
- Unreal 4.18.3
- ue4 socketio 0.7.0

**Comment by getnamo** [comment]
Appears linked to https://github.com/getnamo/socketio-client-ue4/issues/70 See comment from SirakDan.

Note that you're the first other confirmed mac user that is attempting to compile the merged libs, see https://github.com/getnamo/socketio-client-ue4/issues/15 for details.

**Comment by haminjun** [comment]
Merge project is still got error but prebuild output successfully run!
I think merge new prebuild output.

I Solved, Thank you!
