### ISSUE TITLE
Custom use of FSocketIONative crashes on destruction due to SIOLambdaRunnable

### ISSUE THREAD

**Issue by divmgl** [getnamo/socketio-client-ue4#78]
It looks like the instance is attempting to destroy `ConnectionThread` forcibly twice using `delete`, once on `Exit()` and once on destruction of the `FSocketIONative` object.

I'm having all kinds of issues with this garbage collection. I've finally got it to where it's no longer crashing by commenting out `delete` in the `Exit()` function but now the game thread is hanging. I'm going to assume this is because it's waiting for a thread to finish and it never finishes because it needs to be destroyed (or is waiting to be destroyed).

Also, this problem only happens when a successful connection is established. Any thoughts?

**Comment by divmgl** [comment]
https://github.com/getnamo/socketio-client-ue4/issues/60 discusses this problem at length. It seems like it's still happening but only with the native client.

**Comment by divmgl** [comment]
I was able to find a solution to this problem. 

* Comment out `delete this` in `SIOLambdaRunnable::Exit`
* Don't manage the scope of `FSocketIONative` directly. Instead, use `ISocketIOClientModule::Get().NewValidNativePointer()` to create the `TSharedPtr` and manage it for you.
* On the destructor of the object where the pointer lives:

```
~Object::Object {
  Socket->ClearCallbacks();
  ISocketIOClientModule::Get().ReleaseNativePointer(Socket);
  Socket = nullptr;
}
```

No more crashes, no more hanging. Still needs to be a discussion around whether `delete this` is necessary in `SIOLambdaRunnable::Exit`.

**Comment by divmgl** [comment]
Hey, thanks for the write-up! I wish I had better suggestions on how to improve this (I'm fairly new to UE4/C++ development). I'll take a look over the information you've provided me and see if I can submit a PR. Right now things are working pretty well so I haven't wanted to change it. Much appreciated.

**Comment by getnamo** [comment]
has been replaced with https://github.com/getnamo/socketio-client-ue4/commit/1825eedc74d108efaf404250fa8e91d17c3adaf8 in 0.8.4
