### ISSUE TITLE
Link error when use FJsonObject in C++

### ISSUE THREAD

**Issue by vermicelli** [getnamo/socketio-client-ue4#84]
I instantiate a TSharedPtr of FJsonObject and set some fields of it in the GameInstance. Then I got following link error when I compile the project in the Debug Editor mode. (No error when I run the game standalone)

`error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl FJsonObject::SetNumberField(class FString const &,double)" (__imp_?SetNumberField@FJsonObject@@QEAAXAEBVFString@@N@Z`

`error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl FJsonObject::FJsonObject(void)" (__imp_??0FJsonObject@@QEAA@XZ)`

`error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl FJsonObject::~FJsonObject(void)" (__imp_??1FJsonObject@@QEAA@XZ) referenced in function "public: virtual void __cdecl SharedPointerInternals::TReferenceControllerWithDeleter<class FJsonObject,struct SharedPointerInternals::DefaultDeleter<class FJsonObject> >::DestroyObject(void)" (?DestroyObject@?$TReferenceControllerWithDeleter@VFJsonObject@@U?$DefaultDeleter@VFJsonObject@@@SharedPointerInternals@@@SharedPointerInternals@@UEAAXXZ)`

I already had "SocketIOClient" added to the build.cs file.

Engine version: 4.19.2

**Comment by getnamo** [comment]
You'll need to add "Json" module to your project build.cs as FJsonObject is an engine module. Optionally you can add "SIOJson" module which depends on the "Json" module.

**Comment by vermicelli** [comment]
Thanks.
I already have "SIOJson" in my build.cs but errors are still there. Adding "Json" solves this problem.

**Comment by kaelyavel** [comment]
> You'll need to add "Json" module to your project build.cs as FJsonObject is an engine module. Optionally you can add "SIOJson" module which depends on the "Json" module.

This actually fixed my issue. Thank you @getnamo.
