### ISSUE TITLE
Not working with UE4.14 ! 

### ISSUE THREAD

**Issue by omran96** [getnamo/socketio-client-ue4#85]
I did everything, everything in the tutorial and it didn't work! I don't  know what is wrong!, Can you help please ?

**Comment by omran96** [comment]
it Connects to the localHost but no sending or receiving any messages!

**Comment by getnamo** [comment]
When requesting help, consider what the other side needs to know to reproduce the problem you're having. Please be more specific, show what things you've tried, what results you expected (specifics) and where it failed.

**Comment by getnamo** [comment]
Please see https://github.com/getnamo/socketio-client-ue4/releases/tag/0.4.1 for the last plugin build that was supporting 4.14.
