### ISSUE TITLE
How to fix json, that was created with structToJson in BP with nativization build?

### ISSUE THREAD

**Issue by Wadimich** [getnamo/socketio-client-ue4#87]
From #82 fix code is working, but now i got JSON, that appends something from BP (project builded with nativization)
`[2018.06.14-13.03.52:063][465]LogSIOJ: Request (json): POST http://localhost:3001/api/gamePlayers`
```json
{
	"nickname_2_E02ACFF342FE82B2AD11F0BE74E2D4A6": "Tester1234",
	"level_73_1B3AEC0845463993181018AAA766FED4": 1,
	"...": "..."
}
```

What should i do, to remove that added long string after "nickname" etc?
I want it to be like
```json
{
	"nickname": "Tester1234",
	"leve": 1,
	"...": "..."
}
```

**Comment by getnamo** [comment]
There is a function I made exactly for this purpose. If you're using the socket.io methods (e.g. ```USIOJConvert::ToJsonObject```) they will automatically use it (https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SIOJson/Private/SIOJConvert.cpp#L209), but if you're doing custom things (as I'm seeing above) you should be able to trim them via the function ```TrimValueKeyNames()``` (https://github.com/getnamo/socketio-client-ue4/blob/master/Source/SIOJson/Public/SIOJConvert.h#L61)

Btw this only happens for blueprint structs, c++ structs do not have hashed values added to them, but the function is safe to call on both types.

**Comment by Wadimich** [comment]
@getnamo nativization requires that function should be exact the same as blueprint structToJson, i'm edited my custom function, and will test in several minutes.

**Comment by getnamo** [comment]
That looks right to me, nice one.
