### ISSUE TITLE
crash issue

### ISSUE THREAD

**Issue by jinnyum** [getnamo/socketio-client-ue4#89]
used version 0.8.4

socketio plugin scoped connection : on

level_blueprint 
beginplay() -> createSocket (gameinstance custom event)

gameinstance_blueprint
createSocket-> spawnActor (BP_SocketIOActor) -> Set socket Variable;

shutdown Event-> socketVariable -> isValid -> isConnected -> Disconnect;

editor play -> exit -> play -> exit -> play -> exit -> play

Repeat and error.

Fatal Error:
file:c:\engine\source\runtime\core\private\genericplatform\genericplatformmemory.cpp][line:183]
Ran out of memory allocating 328511296231 bytes with alignment 0

**Comment by getnamo** [comment]
Closing due to age and architecture change, re-open if issue persists with latest release.
