### ISSUE TITLE
socket.io namespace

### ISSUE THREAD

**Issue by xxAtrain223** [getnamo/socketio-client-ue4#9]
Hi,
I'm not sure, but I think the plugin is locked to the socket.io namespace, looking through the source code, I think [this line](https://github.com/getnamo/socket.io-client-cpp/blob/9f7e6e0d60ba8ba1768ce8823d581e9dbb87b2d8/src/internal/sio_client_impl.cpp#L209) is the culprit.
This could be by design, so i'd like your input.

**Comment by getnamo** [comment]
Will confirm if this is broken in the next few days.

**Comment by getnamo** [comment]
have you tried a recent build with socket.io server 1.0 or newer?

**Comment by getnamo** [comment]
confirmed working on latest plugin 0.4.0 on the client and socket.io@1.4.0 on the server
