### ISSUE TITLE
The Example Worked ! Tho i don't know how to send to normal IP address 

### ISSUE THREAD

**Issue by omran96** [getnamo/socketio-client-ue4#91]
Hey ! the example worked for the localhost:3000 UE4.16 , but i don't know how to sent udp packets to normal ip (ie 192.168.1.6:8111) , what should i change to make it work ??

**Comment by getnamo** [comment]
socket.io is tcp based websockets only, but you can change your connection endpoint under Address and port in your class defaults as shown in this section https://github.com/getnamo/socketio-client-ue4#how-to-use---bp-basics

If you really want to use udp in the same way this plugin works, there is a very thin wrapper available here: https://github.com/getnamo/udp-ue4

**Comment by omran96** [comment]
I'll try it ! , thank you !
