### ISSUE TITLE
The "On Event" not working

### ISSUE THREAD

**Issue by MarceloxAlves** [getnamo/socketio-client-ue4#96]
The "On Event" not working, in my server node.js have a event of return "update" but not call event "On Event".  Help
![image](https://user-images.githubusercontent.com/5490563/45265397-a5e4f980-b420-11e8-9694-4de1d32437e5.png)

**Comment by getnamo** [comment]
Did you bind your event as shown here? 

https://github.com/getnamo/socketio-client-ue4#how-to-use---bp-basics

If you wish to use the ```On Event``` you need to use bind event with your event name on your _SocketIOClient_ component.

You can also alternatively bind it to a function as shown here

https://github.com/getnamo/socketio-client-ue4#binding-events-to-functions

**Comment by getnamo** [comment]
Closed due to inactivity
