### ISSUE TITLE
ue4.19 crash after emit (plugin version 0.8.9) - duplicate of 102

### ISSUE THREAD

**Issue by fatcloud** [getnamo/socketio-client-ue4#99]
Hello,
Unreal editor crash when I tried to emit a message 2 seconds after On_Connected event
![image](https://user-images.githubusercontent.com/7896433/46277491-e0f8c980-c595-11e8-8802-d4b7b127cef6.png)

And my server DID receive the last words from unreal client
(The "yooo" message printed in console comes from the ToJsonValue box in blueprint)
![image](https://user-images.githubusercontent.com/7896433/46277683-7ac07680-c596-11e8-898d-339d465eb2b0.png)

**Comment by getnamo** [comment]
Also what happens if you use ToJsonValue result directly in the emit.message field without using a casting node?

**Comment by fatcloud** [comment]
Here I upload the log taken just right after the crash
I guess this might be more clear than the one appended in my previous comment
[HelloSocketIO.log](https://github.com/getnamo/socketio-client-ue4/files/2439391/HelloSocketIO.log)

**Comment by getnamo** [comment]
same issue as https://github.com/getnamo/socketio-client-ue4/issues/102. A fix has been merged into master branch, re-pull and compile to get the fix. Will merge other issues before making a new release

**Comment by getnamo** [comment]
see https://github.com/getnamo/socketio-client-ue4/issues/102#issuecomment-434508729 for details. Closing due to work in https://github.com/getnamo/socketio-client-ue4/issues/102
